filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            not:
              equals:
                container.name: "beewaf_sklearn"

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false
