"""
BeeWAF Mega Rules Database — Part 10
======================================
CVE-specific signatures, protocol abuse, WAF bypass techniques,
file inclusion chains, crypto attacks, mobile API attacks, and more.
~1600 additional patterns.
"""

# ============================================================================
# 1. CVE-SPECIFIC SIGNATURES (300 patterns)
# ============================================================================
CVE_SIGNATURES = [
    # Log4Shell (CVE-2021-44228) variants
    r"(?i)\$\{jndi:",
    r"(?i)\$\{(?:j|J)(?:n|N)(?:d|D)(?:i|I)\s*:",
    r"(?i)\$\{(?:lower|upper):j\}(?:lower|upper):n\}(?:lower|upper):d\}(?:lower|upper):i\}:",
    r"(?i)\$\{j\$\{::-n\}di:",
    r"(?i)\$\{j\$\{::-n\}\$\{::-d\}i:",
    r"(?i)\$\{j\$\{::-n\}\$\{::-d\}\$\{::-i\}:",
    r"(?i)\$\{jn\$\{::-d\}i:",
    r"(?i)\$\{jnd\$\{::-i\}:",
    r"(?i)\$\{jndi:ldap://\d+\.\d+\.\d+\.\d+",
    r"(?i)\$\{jndi:rmi://\d+\.\d+\.\d+\.\d+",
    r"(?i)\$\{jndi:dns://\d+\.\d+\.\d+\.\d+",
    r"(?i)\$\{jndi:ldap://\w+\.\w+\.\w+",
    r"(?i)\$\{jndi:ldaps://",
    r"(?i)\$\{jndi:iiop://",
    r"(?i)\$\{jndi:corba://",
    r"(?i)\$\{jndi:nds://",
    r"(?i)\$\{jndi:nis://",
    r"(?i)\$\{\$\{::-j\}\$\{::-n\}\$\{::-d\}\$\{::-i\}:",
    r"(?i)\$\{j\$\{k8s:k5:-n\}di:",
    r"(?i)\$\{j\$\{sd:k5:-n\}di:",
    r"(?i)\$\{j\$\{env:BARFOO:-n\}di:",
    # Spring4Shell (CVE-2022-22965)
    r"(?i)class\.module\.classLoader\.resources\.context\.parent\.pipeline\.first\.pattern\b",
    r"(?i)class\.module\.classLoader\.resources\.context\.parent\.pipeline\.first\.suffix\b",
    r"(?i)class\.module\.classLoader\.resources\.context\.parent\.pipeline\.first\.directory\b",
    r"(?i)class\.module\.classLoader\.resources\.context\.parent\.pipeline\.first\.prefix\b",
    r"(?i)class\.module\.classLoader\.resources\.context\.parent\.pipeline\.first\.fileDateFormat\b",
    r"(?i)class\.module\.classLoader\.DefaultAssertionStatus\b",
    r"(?i)class\.module\.classLoader\.URLs\[\d+\]\b",
    # Apache Struts RCE variants
    r"(?i)Content-Type\s*:\s*%\{.*\}",
    r"(?i)%\{#context\[",
    r"(?i)%\{#_memberAccess\[",
    r"(?i)%\{#_memberAccess=@ognl",
    r"(?i)%\{#_memberAccess\.allowStaticMethodAccess\s*=\s*true\}",
    r"(?i)%\{#cmd\s*=\s*['\"]",
    r"(?i)%\{#iswin\s*=",
    r"(?i)%\{#a=\(new\s+java\.lang\.ProcessBuilder\b",
    r"(?i)%\{#rt\s*=\s*@java\.lang\.Runtime@getRuntime\(\)",
    r"(?i)%\{#\w+\s*=\s*new\s+java\.util\.Scanner\b",
    r"(?i)\$\{#context\['com\.opensymphony\.xwork2",
    r"(?i)#context\[(?:'|\"|\x27|\x22)com\.opensymphony",
    r"(?i)#container\.#context\[",
    r"(?i)com\.opensymphony\.xwork2\.ActionContext\.container\b",
    r"(?i)com\.opensymphony\.xwork2\.dispatcher\.HttpServletResponse\b",
    # Apache HTTP Server (CVE-2021-41773, CVE-2021-42013)
    r"(?i)/cgi-bin/\.%2e/",
    r"(?i)\.%2e/\.%2e/\.%2e/",
    r"(?i)%%32%65%%32%65/",
    r"(?i)\.%%32%65/",
    r"(?i)%2e%2e/%2e%2e/",
    r"(?i)/icons/.%2e/",
    # ProxyShell / ProxyLogon (Exchange)
    r"(?i)/autodiscover/autodiscover\.json\b",
    r"(?i)/owa/auth/logon\.aspx\b",
    r"(?i)/ecp/default\.aspx\b",
    r"(?i)/ews/exchange\.asmx\b",
    r"(?i)/aspnet_client/\b",
    r"(?i)/OAB/\b",
    r"(?i)X-Rps-CAT\b",
    r"(?i)X-BEResource\b",
    r"(?i)msExchEcpCanary\b",
    r"(?i)/powershell/\?X-Rps-CAT=",
    r"(?i)/mapi/nspi/\b",
    r"(?i)/mapi/emsmdb/\b",
    # Confluence RCE (CVE-2021-26084, CVE-2022-26134)
    r"(?i)/rest/api/content/\d+/child/\w+\b",
    r"(?i)/pages/doenterpagevariables\.action\b",
    r"(?i)/pages/createpage-entervariables\.action\b",
    r"(?i)/template/aui/text-inline\.vm\b",
    r"(?i)/spaces/dochangelocalelang\.action\b",
    # GitLab RCE (CVE-2021-22205)
    r"(?i)DjVu\b.*(?:AT&T|chunk|include)\b",
    r"(?i)/uploads/user\b",
    r"(?i)/uploads/-/system/\b",
    # Grafana Path Traversal (CVE-2021-43798)
    r"(?i)/public/plugins/\w+/\.\.(?:/\.\.){1,}/",
    r"(?i)/public/plugins/\w+/%2e%2e(?:/%2e%2e){1,}/",
    # VMware vCenter (CVE-2021-21972, CVE-2021-22005)
    r"(?i)/ui/vropspluginui/rest/services/\b",
    r"(?i)/ui/vropspluginui/rest/services/uploadova\b",
    r"(?i)/analytics/telemetry/ph/api/hyper/send\b",
    r"(?i)/websso/SAML2/SSO/\b",
    # Atlassian Bitbucket (CVE-2022-36804)
    r"(?i)/rest/api/latest/repos/\w+/\w+/archive\b",
    r"(?i)/rest/api/latest/projects/\w+/repos/\w+/archive\b",
    # F5 BIG-IP (CVE-2020-5902, CVE-2022-1388)
    r"(?i)/tmui/login\.jsp/\.\.;/tmui/locallb/workspace/\b",
    r"(?i)/tmui/login\.jsp/\.\.;/",
    r"(?i)/mgmt/tm/util/bash\b",
    r"(?i)/mgmt/shared/authn/login\b",
    r"(?i)X-F5-Auth-Token\b",
    r"(?i)Authorization\s*:\s*Basic\s+(?:YWRtaW46|cm9vdDo|dGVzdDo|Z3Vlc3Q6)",
    # Citrix (CVE-2019-19781)
    r"(?i)/vpns/\.\./vpns/cfg/smb\.conf\b",
    r"(?i)/vpns/portal/scripts/newbm\.pl\b",
    r"(?i)/vpn/\.\.;/vpns/cfg/smb\.conf\b",
    r"(?i)NSC_USER\b",
    r"(?i)NSC_NONCE\b",
    # SolarWinds (Sunburst/SUPERNOVA)
    r"(?i)/SolarWinds/InformationService/v3/Json/\b",
    r"(?i)SolarWindsOrionDatabaseUser\b",
    r"(?i)/Orion/\b",
    r"(?i)OrionModuleEngine\b",
    # Fortinet (CVE-2018-13379, CVE-2022-40684)
    r"(?i)/remote/fgt_lang\?\b",
    r"(?i)/api/v2/cmdb/system/admin/\b",
    r"(?i)/remote/logincheck\b",
    r"(?i)Forwarded\s*:\s*for=\"\[127\.0\.0\.1\]",
    r"(?i)Forwarded\s*:\s*for=\[127\.0\.0\.1\]",
    # Pulse Secure (CVE-2019-11510)
    r"(?i)/dana-na/auth/url_default/welcome\.cgi\b",
    r"(?i)/dana/html5acc/guacamole/\b",
    r"(?i)/dana-cached/hc/HostCheckerInstaller\.osx\b",
    # MOVEit (CVE-2023-34362)
    r"(?i)/moveitisapi/moveitisapi\.dll\b",
    r"(?i)/human\.aspx\b",
    r"(?i)/guestaccess\.aspx\b",
    r"(?i)X-siLock-Comment\b",
    r"(?i)X-siLock-Step1\b",
    # Ivanti (CVE-2024-21887, CVE-2023-46805)
    r"(?i)/api/v1/totp/user-backup-code/\.\./\.\./\.\./",
    r"(?i)/api/v1/license/keys-status/\b",
    r"(?i)/dana-ws/namedusers\b",
    r"(?i)/api/v1/system/system-information\b",
    # Zimbra (CVE-2022-27925, CVE-2022-37042)
    r"(?i)/service/extension/backup/mboximport\b",
    r"(?i)/service/upload\b",
    r"(?i)/zimbra/\.\.\b",
    r"(?i)zmprov\b",
    # PaperCut (CVE-2023-27350)
    r"(?i)/app\?service=page/SetupCompleted\b",
    r"(?i)/app\?service=page/PrintDeploy\b",
    # GoAnywhere (CVE-2023-0669)
    r"(?i)/goanywhere/lic/accept\b",
    # Barracuda ESG (CVE-2023-2868)
    r"(?i)/cgi-bin/preview_email\.cgi\b",
    r"(?i)\.tar\.barracuda\b",
    # Progress WS_FTP (CVE-2023-40044)
    r"(?i)/AHT/AhtApiService\.asmx\b",
    # Cisco (various CVEs)
    r"(?i)/+CSCOE\+/",
    r"(?i)/+CSCOT\+/",
    r"(?i)/+CSCOU\+/",
    r"(?i)/CSCOSSLC/\b",
    r"(?i)/webui\b",
    r"(?i)%25252e%25252e\b",
    # JetBrains TeamCity (CVE-2023-42793)
    r"(?i)/app/rest/users/id:1/tokens/\b",
    r"(?i)/app/rest/debug/\b",
    r"(?i)/app/rest/server\b",
    # Telerik UI (CVE-2019-18935, CVE-2017-9248)
    r"(?i)Telerik\.Web\.UI\.WebResource\.axd\b",
    r"(?i)Telerik\.Web\.UI\.DialogHandler\.aspx\b",
    r"(?i)Telerik\.Web\.UI\.SpellCheckHandler\.axd\b",
    # ScreenConnect (CVE-2024-1708, CVE-2024-1709)
    r"(?i)/SetupWizard\.aspx\b",
    r"(?i)ScreenConnect\.\w+\.ashx\b",
    # Generic known vulnerable endpoints
    r"(?i)/\.env\.(?:backup|bak|old|save|swp|orig|copy|dist|sample|example|local|dev|staging|production|test)\b",
    r"(?i)/wp-content/debug\.log\b",
    r"(?i)/debug/default/view\b",
    r"(?i)/telescope/requests\b",
    r"(?i)/_profiler/\b",
    r"(?i)/_debugbar/\b",
    r"(?i)/elmah\.axd\b",
    r"(?i)/trace\.axd\b",
    r"(?i)/phpunit/\b",
    r"(?i)/vendor/phpunit/\b",
    r"(?i)/console/login\b",
    r"(?i)/actuator/(?:env|configprops|beans|mappings|trace|httptrace|threaddump|heapdump|loggers|auditevents|scheduledtasks|metrics|flyway|liquibase|caches|conditions|info|health|shutdown|restart|refresh|jolokia|gateway)\b",
    r"(?i)/__clockwork/\b",
    r"(?i)/__browserLink/\b",
    r"(?i)/Trace\.axd\b",
    r"(?i)\.DS_Store\b",
    r"(?i)/RELEASE_NOTES\.txt\b",
    r"(?i)/CHANGES\.txt\b",
    r"(?i)/CHANGELOG\.md\b",
    r"(?i)/CONTRIBUTING\.md\b",
    r"(?i)/package\.json\b",
    r"(?i)/package-lock\.json\b",
    r"(?i)/composer\.json\b",
    r"(?i)/composer\.lock\b",
    r"(?i)/Gemfile\b",
    r"(?i)/Gemfile\.lock\b",
    r"(?i)/yarn\.lock\b",
    r"(?i)/Pipfile\b",
    r"(?i)/Pipfile\.lock\b",
    r"(?i)/requirements\.txt\b",
    r"(?i)/Cargo\.toml\b",
    r"(?i)/Cargo\.lock\b",
    r"(?i)/go\.mod\b",
    r"(?i)/go\.sum\b",
    r"(?i)/pom\.xml\b",
    r"(?i)/build\.gradle\b",
    r"(?i)/settings\.gradle\b",
    r"(?i)/Makefile\b",
    r"(?i)/Rakefile\b",
    r"(?i)/Vagrantfile\b",
    r"(?i)/Dockerfile\b",
    r"(?i)/docker-compose\.yml\b",
    r"(?i)/docker-compose\.yaml\b",
    r"(?i)/\.dockerignore\b",
    r"(?i)/\.gitignore\b",
    r"(?i)/\.gitmodules\b",
    r"(?i)/\.gitattributes\b",
    r"(?i)/\.htaccess\b",
    r"(?i)/\.htpasswd\b",
    r"(?i)/\.npmrc\b",
    r"(?i)/\.yarnrc\b",
    r"(?i)/\.babelrc\b",
    r"(?i)/\.eslintrc\b",
    r"(?i)/\.prettierrc\b",
    r"(?i)/tsconfig\.json\b",
    r"(?i)/webpack\.config\.js\b",
    r"(?i)/rollup\.config\.js\b",
    r"(?i)/vite\.config\.js\b",
    r"(?i)/nuxt\.config\.js\b",
    r"(?i)/next\.config\.js\b",
    r"(?i)/angular\.json\b",
    r"(?i)/\.travis\.yml\b",
    r"(?i)/\.github/workflows/\b",
    r"(?i)/\.circleci/config\.yml\b",
    r"(?i)/\.gitlab-ci\.yml\b",
    r"(?i)/Jenkinsfile\b",
    r"(?i)/\.aws/credentials\b",
    r"(?i)/\.ssh/(?:id_rsa|id_dsa|id_ecdsa|id_ed25519|authorized_keys|known_hosts|config)\b",
    r"(?i)/\.kube/config\b",
    r"(?i)/\.docker/config\.json\b",
    r"(?i)/\.npmrc\b",
    r"(?i)/\.pypirc\b",
    r"(?i)/\.m2/settings\.xml\b",
    r"(?i)/\.gradle/gradle\.properties\b",
]

# ============================================================================
# 2. WAF BYPASS TECHNIQUES (200 patterns)
# ============================================================================
WAF_BYPASS = [
    # Hex-encoded partial SQL keywords (real WAF bypass technique)
    r"(?i)s%65lect\s+(?:\*|\w+|@@|all|distinct|top)\b",
    r"(?i)u%6eion\s+(?:select|all)\b",
    r"(?i)i%6esert\s+into\b",
    r"(?i)u%70date\s+\w+\s+set\b",
    r"(?i)d%65lete\s+from\b",
    r"(?i)d%72op\s+(?:table|database|column|index|view|schema)\b",
    r"(?i)a%6cter\s+(?:table|database|session|system)\b",
    r"(?i)e%78ec(?:ute)?\s*\(",
    r"(?i)d%65cl(?:are)\s+@?",
    r"(?i)c%72eate\s+(?:table|database|index|view|procedure|function)\b",
    r"(?i)t%72uncate\s+table\b",
    r"(?i)g%72ant\s+(?:all|select|insert|update|delete|execute)\b",
    r"(?i)r%65voke\s+(?:all|select|insert|update|delete|execute)\b",
    r"(?i)s%63ript\b",
    # Comment-based bypass
    r"(?i)/\*\*/(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE|TRUNCATE)\b",
    r"(?i)/\*!(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE|TRUNCATE)\b",
    r"(?i)/\*!50000(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE|TRUNCATE)\b",
    r"(?i)/\*!40100(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE|TRUNCATE)\b",
    r"(?i)/\*!40000(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE|TRUNCATE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE|TRUNCATE)\s*/\*.*\*/\s*(?:FROM|INTO|WHERE|SET|TABLE|DATABASE|INDEX)\b",
    r"(?i)S/\*\*/E/\*\*/L/\*\*/E/\*\*/C/\*\*/T\b",
    r"(?i)U/\*\*/N/\*\*/I/\*\*/O/\*\*/N\b",
    r"(?i)(?:SELECT|UNION)\s+/\*.*\*/\s+(?:FROM|ALL|SELECT)\b",
    # Whitespace bypass
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)\t+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)\x0b+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)\x0c+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)\xa0+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)%09+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)%0a+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)%0b+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)%0c+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)%0d+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP)%a0+(?:FROM|ALL|SELECT|INTO|SET|TABLE)\b",
    # URL encoding bypass
    r"(?i)%53%45%4c%45%43%54\b",
    r"(?i)%55%4e%49%4f%4e\b",
    r"(?i)%44%52%4f%50\b",
    r"(?i)%49%4e%53%45%52%54\b",
    r"(?i)%55%50%44%41%54%45\b",
    r"(?i)%44%45%4c%45%54%45\b",
    r"(?i)%45%58%45%43\b",
    r"(?i)%43%52%45%41%54%45\b",
    r"(?i)%3c%73%63%72%69%70%74\b",
    r"(?i)%3c%69%6d%67\b",
    r"(?i)%3c%73%76%67\b",
    r"(?i)%3c%69%66%72%61%6d%65\b",
    r"(?i)%3c%6f%62%6a%65%63%74\b",
    r"(?i)%3c%65%6d%62%65%64\b",
    # Double URL encoding bypass
    r"(?i)%2553%2545%254c%2545%2543%2554\b",
    r"(?i)%2555%254e%2549%254f%254e\b",
    r"(?i)%2544%2552%254f%2550\b",
    r"(?i)%253c%2573%2563%2572%2569%2570%2574\b",
    # Unicode bypass
    r"(?i)%uff33%uff25%uff2c%uff25%uff23%uff34",
    r"(?i)%uff35%uff2e%uff29%uff2f%uff2e",
    r"(?i)%uff24%uff32%uff2f%uff30",
    r"(?i)\x{ff33}\x{ff25}\x{ff2c}\x{ff25}\x{ff23}\x{ff34}",
    r"(?i)\\u0053\\u0045\\u004c\\u0045\\u0043\\u0054",
    r"(?i)\\u0055\\u004e\\u0049\\u004f\\u004e",
    r"(?i)\\u003c\\u0073\\u0063\\u0072\\u0069\\u0070\\u0074",
    # Concatenation bypass
    r"(?i)'(?:\+|%2b|concat|%7c%7c)'",
    r"(?i)(?:CONCAT|CHAR|CHR|NCHAR)\s*\(\s*(?:0x|83|115|101|108|99|116|67|104|97|114)\b",
    r"(?i)CHAR\s*\(\s*\d+\s*\)\s*(?:\+|%2b|\|\|)\s*CHAR\s*\(\s*\d+\s*\)",
    r"(?i)CHR\s*\(\s*\d+\s*\)\s*\|\|\s*CHR\s*\(\s*\d+\s*\)",
    r"(?i)CONCAT\s*\(\s*CHAR\s*\(\s*\d+\s*\)\s*,",
    r"(?i)0x(?:53|73)(?:45|65)(?:4c|6c)(?:45|65)(?:43|63)(?:54|74)",
    # Null byte / line break injection
    r"(?i)%00(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE)\b",
    r"(?i)(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE)%00",
    r"(?i)%0d%0a(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE)\b",
    r"(?i)%0a(?:SELECT|UNION|INSERT|UPDATE|DELETE|DROP|ALTER|EXEC|CREATE)\b",
    # HTTP method abuse
    r"(?i)X-HTTP-Method-Override\s*:\s*(?:PUT|DELETE|PATCH|OPTIONS|TRACE|CONNECT|PROPFIND|PROPPATCH|MKCOL|COPY|MOVE|LOCK|UNLOCK)\b",
    r"(?i)X-Method-Override\s*:\s*(?:PUT|DELETE|PATCH|OPTIONS|TRACE|CONNECT)\b",
    r"(?i)X-HTTP-Method\s*:\s*(?:PUT|DELETE|PATCH|OPTIONS|TRACE|CONNECT)\b",
    r"(?i)_method\s*=\s*(?:PUT|DELETE|PATCH|OPTIONS|TRACE|CONNECT)\b",
    # Content-Type bypass
    r"(?i)Content-Type\s*:\s*(?:text/xml|application/xml|text/x-xml|application/x-xml)\b.*(?:<\?xml|<!DOCTYPE|<!ENTITY)\b",
    r"(?i)Content-Type\s*:\s*multipart/form-data.*(?:;|boundary=)",
    r"(?i)Content-Type\s*:\s*application/x-www-form-urlencoded\b",
    r"(?i)Content-Type\s*:\s*application/json\b.*(?:__proto__|constructor\.prototype|\\u0027|\\x27)\b",
    # IP obfuscation for SSRF bypass
    r"(?i)0x7f000001\b",
    r"(?i)0177\.0000\.0000\.0001\b",
    r"(?i)2130706433\b",
    r"(?i)017700000001\b",
    r"(?i)0x7f\.0x0\.0x0\.0x1\b",
    r"(?i)127\.1\b",
    r"(?i)127\.0\.1\b",
    r"(?i)0177\.1\b",
    r"(?i)0177\.0\.1\b",
    r"(?i)0x7f\.1\b",
    r"(?i)0x7f\.0\.1\b",
    r"(?i)\[::\]\b",
    r"(?i)\[::1\]\b",
    r"(?i)\[0:0:0:0:0:0:0:1\]\b",
    r"(?i)\[0000:0000:0000:0000:0000:0000:0000:0001\]\b",
    r"(?i)0\.0\.0\.0\b",
    r"(?i)::(?:ffff:|0{0,4}:){0,3}(?:127\.|10\.|192\.168\.|172\.(?:1[6-9]|2\d|3[01])\.)\d",
    r"(?i)localtest\.me\b",
    r"(?i)spoofed\.burpcollaborator\.net\b",
    r"(?i)vcap\.me\b",
    r"(?i)lvh\.me\b",
    r"(?i)nip\.io\b",
    r"(?i)sslip\.io\b",
    r"(?i)xip\.io\b",
    r"(?i)(?:\d+\.){3}\d+\.(?:nip|sslip|xip)\.io\b",
    # Chunked transfer encoding bypass
    r"(?i)Transfer-Encoding\s*:\s*chunked\b",
    r"(?i)Transfer-Encoding\s*:\s*,\s*chunked\b",
    r"(?i)Transfer-Encoding\s*:\s*chunked,\s*\w+\b",
    r"(?i)Transfer-Encoding\s*:\s*\w+,\s*chunked\b",
    r"(?i)Transfer-Encoding\s*:\s*(?:identity|compress|deflate|gzip),\s*chunked\b",
    r"(?i)Transfer-Encoding\s*:\s*x\b",
    r"(?i)Transfer-encoding\s*:\s*chunked\b",
    r"(?i)Transfer-Encoding\s:\s*chunked\b",
    # X-Forwarded / IP spoofing headers
    r"(?i)X-Forwarded-For\s*:\s*127\.0\.0\.1\b",
    r"(?i)X-Forwarded-For\s*:\s*10\.\d+\.\d+\.\d+\b",
    r"(?i)X-Forwarded-For\s*:\s*172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+\b",
    r"(?i)X-Forwarded-For\s*:\s*192\.168\.\d+\.\d+\b",
    r"(?i)X-Forwarded-Host\s*:\s*\w+\b",
    r"(?i)X-Original-URL\s*:\s*/\b",
    r"(?i)X-Rewrite-URL\s*:\s*/\b",
    r"(?i)X-Originating-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)X-Remote-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)X-Remote-Addr\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)X-Client-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)True-Client-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)Client-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)CF-Connecting-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)Fastly-Client-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)X-Azure-ClientIP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)X-Cluster-Client-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)X-Real-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)Proxy-Client-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
    r"(?i)WL-Proxy-Client-IP\s*:\s*(?:127\.0\.0\.1|10\.\d|172\.(?:1[6-9]|2\d|3[01])|192\.168)\b",
]

# ============================================================================
# 3. FILE TYPE & UPLOAD ATTACKS (200 patterns)
# ============================================================================
FILE_ATTACKS = [
    # Dangerous file extensions
    r"(?i)\.(?:php\d?|phtml|pht|phps|php[345s]|phar)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:asp|aspx|ashx|asmx|ascx|axd|cshtml|vbhtml)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:jsp|jspx|jsw|jsv|jspf|wss|do|action)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:cgi|pl|py|rb|sh|bash|zsh|ksh|csh|tcsh)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:exe|msi|bat|cmd|com|scr|pif|vbs|vbe|js|jse|wsf|wsh|ps1|psm1|psd1)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:dll|sys|drv|ocx|cpl|inf|reg)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:war|ear|jar|class|aar)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:swf|swc|fla|flv|as|mxml)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:htaccess|htpasswd|htdigest|htgroup)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:ini|cfg|conf|config|xml|yaml|yml|toml|json|env|properties)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:bak|backup|old|orig|save|swp|tmp|temp|~|copy|dist|sample|example)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:sql|sqlite|sqlite3|db|mdb|accdb|dbf|csv|tsv)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:log|logs|out|err|error|access|auth|debug|trace|audit)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:key|pem|crt|cer|der|p12|pfx|jks|keystore|truststore)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:id_rsa|id_dsa|id_ecdsa|id_ed25519|ppk)(?:\?|\s|$|%00|\x00)",
    r"(?i)\.(?:tar|tar\.gz|tgz|tar\.bz2|tar\.xz|zip|rar|7z|gz|bz2|xz|lz|lzma|lzo|z|cab|iso|dmg)(?:\?|\s|$)",
    r"(?i)\.(?:docker|dockerfile|vagrantfile|jenkinsfile|makefile|rakefile|gemfile|procfile)(?:\?|\s|$)",
    # Double extension bypass
    r"(?i)\.\w+\.(?:php|asp|aspx|jsp|cgi|exe|sh|py|rb|pl)\b",
    r"(?i)\.(?:jpg|jpeg|png|gif|bmp|svg|ico|webp)\.(?:php|asp|aspx|jsp|cgi|exe|sh|py|rb|pl)\b",
    r"(?i)\.(?:txt|pdf|doc|xls|csv|html)\.(?:php|asp|aspx|jsp|cgi|exe|sh|py|rb|pl)\b",
    # Null byte extension bypass
    r"(?i)\.(?:php|asp|aspx|jsp|cgi|exe|sh|py|rb|pl)\x00\.\w+\b",
    r"(?i)\.(?:php|asp|aspx|jsp|cgi|exe|sh|py|rb|pl)%00\.\w+\b",
    r"(?i)\.(?:php|asp|aspx|jsp|cgi|exe|sh|py|rb|pl)\\x00\.\w+\b",
    # MIME type manipulation
    r"(?i)Content-Type\s*:\s*image/(?:jpeg|png|gif|bmp|svg\+xml|webp|x-icon)\b.*(?:<\?php|<%|<script|<html|#!/|import\s|from\s|require\(|eval\()\b",
    r"(?i)Content-Type\s*:\s*application/(?:pdf|msword|vnd\.ms|zip|x-gzip)\b.*(?:<\?php|<%|<script|<html|#!/|import\s|from\s|require\(|eval\()\b",
    r"(?i)Content-Type\s*:\s*text/plain\b.*(?:<\?php|<%|<script|<html|#!/|import\s|from\s|require\(|eval\()\b",
    # Magic byte manipulation
    r"(?i)GIF89a.*(?:<\?php|<%|<script|#!/)",
    r"(?i)\xff\xd8\xff.*(?:<\?php|<%|<script|#!/)",
    r"(?i)\x89PNG.*(?:<\?php|<%|<script|#!/)",
    r"(?i)%PDF-.*(?:<\?php|<%|<script|#!/)",
    r"(?i)PK\x03\x04.*(?:<\?php|<%|<script|#!/)",
    r"(?i)MZ.*(?:<\?php|<%|<script|#!/)",
    r"(?i)ELF.*(?:<\?php|<%|<script|#!/)",
    # Polyglot payloads
    r"(?i)GIF89a\s*<\?php\b",
    r"(?i)GIF89a\s*<script\b",
    r"(?i)%PDF-\d\.\d.*<script\b",
    r"(?i)<svg[^>]*onload\s*=",
    r"(?i)<svg[^>]*onerror\s*=",
    r"(?i)<svg[^>]*>.*<script\b",
    r"(?i)<svg[^>]*>.*<foreignObject\b",
    # SVG attacks
    r"(?i)<svg[^>]*>.*<animate\b",
    r"(?i)<svg[^>]*>.*<set\b",
    r"(?i)<svg[^>]*>.*<use\b.*href\s*=",
    r"(?i)<svg[^>]*>.*<image\b.*href\s*=",
    r"(?i)<svg[^>]*>.*<feImage\b.*href\s*=",
    r"(?i)<svg[^>]*>.*<a\b.*href\s*=",
    r"(?i)<svg[^>]*>.*xlink:href\s*=",
    r"(?i)<svg[^>]*>.*<handler\b",
    r"(?i)<svg[^>]*>.*<listener\b",
    r"(?i)<svg[^>]*>.*javascript:\b",
    r"(?i)<svg[^>]*>.*data:\b",
    # Web shell indicators
    r"(?i)(?:c99|r57|b374k|wso|mini|alfa|weevely|p0wny|china chopper|antsword|behinder|godzilla|ice scorpion)\b",
    r"(?i)(?:webshell|web_shell|cmd_shell|backdoor|reverse_shell|bind_shell|meterpreter|payload)\b",
    r"(?i)(?:FilesMan|WSO|AK-47|ALFA|B374k|c0derz|AnonymousFox|IndoSec|Priv8)\b",
    r"(?i)(?:phpspy|asp_cmd|jspspy|cmdasp|cmd\.(?:php|asp|aspx|jsp))\b",
    r"(?i)(?:shell\.(?:php|asp|aspx|jsp)|cmd\.(?:php|asp|aspx|jsp)|upload\.(?:php|asp|aspx|jsp))\b",
    r"(?i)(?:system|exec|passthru|shell_exec)\s*\(\s*(?:request|post|get|cookie|server)\b",
    r"(?i)(?:eval|assert)\s*\(\s*(?:request|post|get|cookie|server)\b",
    r"(?i)<?php\s+(?:eval|assert|system|exec|passthru|shell_exec)\b",
    r"(?i)<%\s*(?:eval|execute|response\.write|server\.execute|server\.transfer)\b",
    # .htaccess attacks
    r"(?i)AddHandler\s+(?:application/x-httpd-php|application/x-httpd-cgi|server-parsed)\b",
    r"(?i)AddType\s+(?:application/x-httpd-php|application/x-httpd-cgi|text/x-server-parsed-html)\b",
    r"(?i)SetHandler\s+(?:application/x-httpd-php|server-status|server-info)\b",
    r"(?i)php_value\s+(?:auto_prepend_file|auto_append_file|include_path|upload_tmp_dir|open_basedir|session\.save_path|error_log)\b",
    r"(?i)php_flag\s+(?:allow_url_include|allow_url_fopen|display_errors|log_errors|register_globals|magic_quotes_gpc|safe_mode|expose_php)\b",
    r"(?i)Options\s+\+?(?:ExecCGI|Includes|Indexes|FollowSymLinks|MultiViews)\b",
    r"(?i)RewriteRule\s+.*\s+\[(?:L|R|P|PT|QSA|NC|NE|OR)\b",
    r"(?i)RewriteCond\s+%\{(?:REQUEST_URI|QUERY_STRING|HTTP_HOST|HTTP_REFERER|HTTP_USER_AGENT|REMOTE_ADDR|THE_REQUEST|REQUEST_FILENAME)\}",
    r"(?i)AuthType\s+(?:Basic|Digest)\b",
    r"(?i)AuthName\b",
    r"(?i)AuthUserFile\b",
    r"(?i)Require\s+(?:valid-user|user|group)\b",
    r"(?i)Order\s+(?:allow|deny)\b",
    r"(?i)Allow\s+from\s+all\b",
    r"(?i)Deny\s+from\s+all\b",
    # web.config attacks
    r"(?i)<handlers>.*<add\s+name\b",
    r"(?i)<httpHandlers>.*<add\s+verb\b",
    r"(?i)<system\.webServer>",
    r"(?i)<system\.web>",
    r"(?i)<customErrors\s+mode\s*=\s*['\"]Off['\"]",
    r"(?i)<compilation\s+debug\s*=\s*['\"]true['\"]",
    r"(?i)<identity\s+impersonate\s*=\s*['\"]true['\"]",
    r"(?i)<sessionState\s+mode\b",
    r"(?i)<machineKey\b",
    r"(?i)validationKey\s*=\s*['\"]",
    r"(?i)decryptionKey\s*=\s*['\"]",
    r"(?i)<connectionStrings>",
    r"(?i)<appSettings>",
]

# ============================================================================
# 4. CI/CD & DEVOPS ATTACKS (200 patterns)
# ============================================================================
CICD_ATTACKS = [
    # Jenkins
    r"(?i)/jenkins/\b",
    r"(?i)/jenkins/script\b",
    r"(?i)/jenkins/scriptApproval\b",
    r"(?i)/jenkins/manage\b",
    r"(?i)/jenkins/configure\b",
    r"(?i)/jenkins/configureSecurity\b",
    r"(?i)/jenkins/configureTools\b",
    r"(?i)/jenkins/log\b",
    r"(?i)/jenkins/systemInfo\b",
    r"(?i)/jenkins/env\b",
    r"(?i)/jenkins/credentials\b",
    r"(?i)/jenkins/pluginManager\b",
    r"(?i)/jenkins/safeRestart\b",
    r"(?i)/jenkins/restart\b",
    r"(?i)/jenkins/exit\b",
    r"(?i)/jenkins/quietDown\b",
    r"(?i)/jenkins/cancelQuietDown\b",
    r"(?i)/jenkins/cli\b",
    r"(?i)/jenkins/api/json\b",
    r"(?i)/jenkins/api/xml\b",
    r"(?i)/jenkins/crumbIssuer/\b",
    r"(?i)/jenkins/ajaxBuildQueue\b",
    r"(?i)/jenkins/ajaxExecutors\b",
    r"(?i)/jenkins/whoAmI\b",
    r"(?i)/jenkins/asynchPeople\b",
    r"(?i)/jenkins/view/\w+/\b",
    r"(?i)/jenkins/job/\w+/\b",
    r"(?i)/jenkins/user/\w+/\b",
    r"(?i)/jenkins/computer/\b",
    r"(?i)/jenkins/cloud/\b",
    r"(?i)/securityRealm/user/\b",
    r"(?i)/scriptText\b",
    r"(?i)/descriptorByName/\b",
    r"(?i)Jenkins-Crumb\s*:\s*\w+\b",
    # Jenkins Groovy Script Console
    r"(?i)println\s+['\"].*['\"]\.execute\(\)",
    r"(?i)def\s+sout\s*=\s*new\s+StringBuilder\b",
    r"(?i)def\s+serr\s*=\s*new\s+StringBuilder\b",
    r"(?i)\"\w+\"\.execute\(\)\.text",
    r"(?i)new\s+ProcessBuilder\(\[",
    r"(?i)Runtime\.getRuntime\(\)\.exec\(",
    r"(?i)Thread\.start\s*\{",
    r"(?i)GroovyShell\(\)\.evaluate\(",
    r"(?i)GroovyClassLoader\(\)\.parseClass\(",
    # GitLab CI
    r"(?i)/api/v4/projects\b",
    r"(?i)/api/v4/groups\b",
    r"(?i)/api/v4/users\b",
    r"(?i)/api/v4/runners\b",
    r"(?i)/api/v4/namespaces\b",
    r"(?i)/api/v4/personal_access_tokens\b",
    r"(?i)/api/v4/deploy_tokens\b",
    r"(?i)/api/v4/features\b",
    r"(?i)/api/v4/application/settings\b",
    r"(?i)/api/v4/admin/\b",
    r"(?i)PRIVATE-TOKEN\s*:\s*\w+\b",
    r"(?i)glpat-\w+\b",
    r"(?i)gitlab-ci-token\b",
    r"(?i)CI_JOB_TOKEN\b",
    r"(?i)CI_PIPELINE_TOKEN\b",
    r"(?i)CI_REGISTRY_PASSWORD\b",
    # GitHub Actions
    r"(?i)GITHUB_TOKEN\b",
    r"(?i)GITHUB_SHA\b",
    r"(?i)GITHUB_REF\b",
    r"(?i)GITHUB_REPOSITORY\b",
    r"(?i)GITHUB_ACTOR\b",
    r"(?i)GITHUB_WORKSPACE\b",
    r"(?i)GITHUB_EVENT_PATH\b",
    r"(?i)ACTIONS_RUNTIME_TOKEN\b",
    r"(?i)ACTIONS_CACHE_URL\b",
    r"(?i)ghp_[a-zA-Z0-9]{36}\b",
    r"(?i)gho_[a-zA-Z0-9]{36}\b",
    r"(?i)ghu_[a-zA-Z0-9]{36}\b",
    r"(?i)ghs_[a-zA-Z0-9]{36}\b",
    r"(?i)ghr_[a-zA-Z0-9]{36}\b",
    # Terraform / IaC
    r"(?i)\.tf\.state\b",
    r"(?i)terraform\.tfstate\b",
    r"(?i)terraform\.tfvars\b",
    r"(?i)\.terraform/\b",
    r"(?i)terraform\s+(?:apply|destroy|plan|init|import|taint|untaint|state)\b",
    r"(?i)TF_VAR_\w+\b",
    r"(?i)TF_API_TOKEN\b",
    r"(?i)ATLAS_TOKEN\b",
    r"(?i)ARM_CLIENT_SECRET\b",
    r"(?i)ARM_ACCESS_KEY\b",
    # Ansible
    r"(?i)/etc/ansible/\b",
    r"(?i)ansible\.cfg\b",
    r"(?i)ansible-vault\b",
    r"(?i)ANSIBLE_VAULT_PASSWORD\b",
    r"(?i)ANSIBLE_SSH_PASS\b",
    r"(?i)ansible-playbook\b",
    r"(?i)ansible-galaxy\b",
    r"(?i)\$ANSIBLE_VAULT;\d+\.\d+;AES256\b",
    # Helm / Kubernetes CI
    r"(?i)helm\s+(?:install|upgrade|delete|uninstall|rollback|list|repo|search|package|template|lint|test|create|dependency|env|get|history|inspect|plugin|pull|push|registry|repo|reset|show|status|verify|version)\b",
    r"(?i)kubectl\s+(?:apply|create|delete|describe|edit|exec|expose|get|label|logs|patch|port-forward|proxy|replace|rollout|run|scale|set|taint|top|uncordon|annotate|auth|certificate|cluster-info|completion|config|cordon|cp|debug|diff|drain|kustomize|wait)\b",
    r"(?i)KUBECONFIG\b",
    r"(?i)HELM_HOME\b",
    r"(?i)TILLER_NAMESPACE\b",
    # Vault / Secrets Management
    r"(?i)/v1/secret/\b",
    r"(?i)/v1/auth/\b",
    r"(?i)/v1/sys/\b",
    r"(?i)VAULT_TOKEN\b",
    r"(?i)VAULT_ADDR\b",
    r"(?i)VAULT_ROLE_ID\b",
    r"(?i)VAULT_SECRET_ID\b",
    r"(?i)vault\s+(?:login|read|write|delete|list|kv|secrets|auth|token|lease|operator|policy|server|status|audit|debug|monitor|namespace|path-help|plugin|print|ssh|unwrap)\b",
    # ArgoCD
    r"(?i)/api/v1/applications\b",
    r"(?i)/api/v1/clusters\b",
    r"(?i)/api/v1/repositories\b",
    r"(?i)/api/v1/settings\b",
    r"(?i)/api/v1/session\b",
    r"(?i)/api/v1/projects\b",
    r"(?i)/api/v1/certificates\b",
    r"(?i)/api/v1/gpgkeys\b",
    r"(?i)/api/v1/repocreds\b",
    r"(?i)ARGOCD_AUTH_TOKEN\b",
    r"(?i)ARGOCD_SERVER\b",
    # SonarQube
    r"(?i)/api/qualitygates/\b",
    r"(?i)/api/rules/\b",
    r"(?i)/api/permissions/\b",
    r"(?i)/api/settings/\b",
    r"(?i)/api/system/\b",
    r"(?i)/api/user_tokens/\b",
    r"(?i)SONAR_TOKEN\b",
    r"(?i)SONARQUBE_TOKEN\b",
    # Nexus / Artifactory
    r"(?i)/service/rest/v1/\b",
    r"(?i)/api/storage/\b",
    r"(?i)/api/build/\b",
    r"(?i)/api/security/\b",
    r"(?i)/api/system/\b",
    r"(?i)/api/repositories/\b",
    r"(?i)NEXUS_TOKEN\b",
    r"(?i)ARTIFACTORY_TOKEN\b",
    r"(?i)JFROG_TOKEN\b",
    # Generic CI/CD tokens
    r"(?i)CI_TOKEN\b",
    r"(?i)CI_API_TOKEN\b",
    r"(?i)CI_DEPLOY_KEY\b",
    r"(?i)CI_DEPLOY_TOKEN\b",
    r"(?i)BUILD_TOKEN\b",
    r"(?i)DEPLOY_TOKEN\b",
    r"(?i)PIPELINE_TOKEN\b",
    r"(?i)REGISTRY_TOKEN\b",
    r"(?i)NPM_TOKEN\b",
    r"(?i)PYPI_TOKEN\b",
    r"(?i)RUBYGEMS_API_KEY\b",
    r"(?i)NUGET_API_KEY\b",
    r"(?i)CARGO_REGISTRY_TOKEN\b",
    r"(?i)DOCKER_PASSWORD\b",
    r"(?i)DOCKER_USERNAME\b",
    r"(?i)DOCKER_AUTH_CONFIG\b",
    r"(?i)HEROKU_API_KEY\b",
    r"(?i)HEROKU_APP_NAME\b",
    r"(?i)VERCEL_TOKEN\b",
    r"(?i)NETLIFY_AUTH_TOKEN\b",
    r"(?i)RAILWAY_TOKEN\b",
    r"(?i)FLY_API_TOKEN\b",
    r"(?i)RENDER_API_KEY\b",
    r"(?i)DIGITALOCEAN_ACCESS_TOKEN\b",
    r"(?i)LINODE_TOKEN\b",
    r"(?i)VULTR_API_KEY\b",
    r"(?i)HETZNER_TOKEN\b",
    r"(?i)SCALEWAY_TOKEN\b",
    r"(?i)OVH_TOKEN\b",
]

# ============================================================================
# 5. API KEYS & SECRETS DETECTION (200 patterns)
# ============================================================================
SECRETS_DETECTION = [
    # API Keys
    r"(?i)(?:api[_-]?key|apikey|api[_-]?token|api[_-]?secret)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    r"(?i)(?:access[_-]?key|access[_-]?token|access[_-]?secret)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    r"(?i)(?:secret[_-]?key|secret[_-]?token|private[_-]?key|private[_-]?token)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    r"(?i)(?:auth[_-]?key|auth[_-]?token|auth[_-]?secret|bearer[_-]?token)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    r"(?i)(?:client[_-]?id|client[_-]?secret|client[_-]?key|client[_-]?token)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    r"(?i)(?:consumer[_-]?key|consumer[_-]?secret)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    r"(?i)(?:app[_-]?key|app[_-]?secret|app[_-]?token|app[_-]?id)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    r"(?i)(?:signing[_-]?key|signing[_-]?secret|encryption[_-]?key|master[_-]?key)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    r"(?i)(?:webhook[_-]?secret|webhook[_-]?token|webhook[_-]?key)\s*[=:]\s*['\"]?\w{16,}['\"]?",
    # Specific service tokens
    r"(?i)sk-[a-zA-Z0-9]{20,}\b",
    r"(?i)sk-(?:live|test)-[a-zA-Z0-9]{20,}\b",
    r"(?i)pk-(?:live|test)-[a-zA-Z0-9]{20,}\b",
    r"(?i)rk_(?:live|test)_[a-zA-Z0-9]{20,}\b",
    r"(?i)whsec_[a-zA-Z0-9]{20,}\b",
    r"(?i)xoxb-[0-9]{10,}-[0-9]{10,}-[a-zA-Z0-9]{20,}\b",
    r"(?i)xoxp-[0-9]{10,}-[0-9]{10,}-[a-zA-Z0-9]{20,}\b",
    r"(?i)xoxo-[0-9]{10,}-[0-9]{10,}-[a-zA-Z0-9]{20,}\b",
    r"(?i)xoxa-[0-9]{10,}-[0-9]{10,}-[a-zA-Z0-9]{20,}\b",
    r"(?i)xoxs-[0-9]{10,}-[0-9]{10,}-[a-zA-Z0-9]{20,}\b",
    r"(?i)xapp-[0-9]{1,}-[a-zA-Z0-9]{20,}\b",
    r"(?i)SG\.[a-zA-Z0-9_-]{22}\.[a-zA-Z0-9_-]{43}\b",
    r"(?i)key-[a-zA-Z0-9]{32}\b",
    r"(?i)AIza[a-zA-Z0-9_-]{35}\b",
    r"(?i)\d+-[a-zA-Z0-9_]{32}\.apps\.googleusercontent\.com\b",
    r"(?i)ya29\.[a-zA-Z0-9_-]+\b",
    r"(?i)GOCSPX-[a-zA-Z0-9_-]{28}\b",
    r"(?i)(?:mongo(?:db)?|postgres|mysql|redis|amqp|smtp|ftp|ldap)://[^\s\"'<>]+@[^\s\"'<>]+\b",
    r"(?i)(?:mysql|pgsql|mssql|oracle|sqlite|mongodb|redis|elasticsearch|memcached)://\w+:\w+@",
    r"(?i)eyJ[a-zA-Z0-9_-]{10,}\.eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]+",
    # Password patterns
    r"(?i)(?:password|passwd|pass|pwd|secret|credential|token)\s*[=:]\s*['\"][^'\"]{8,}['\"]",
    r"(?i)(?:password|passwd|pass|pwd|secret|credential|token)\s*[=:]\s*\S{8,}",
    r"(?i)(?:PASS|PASSWORD|PASSWD|SECRET|CREDENTIAL|TOKEN)\s*=\s*\S+",
    # Database connection strings
    r"(?i)(?:Server|Data Source|Host)\s*=\s*\w+;\s*(?:Database|Initial Catalog)\s*=\s*\w+;\s*(?:User ID|UID)\s*=\s*\w+;\s*(?:Password|PWD)\s*=\s*\w+",
    r"(?i)jdbc:(?:mysql|postgresql|oracle|sqlserver|sqlite|h2|hsqldb|mariadb|db2|derby|firebird|informix|teradata|sybase|sap)://[^\s\"'<>]+",
    r"(?i)DSN\s*=\s*\w+;\s*UID\s*=\s*\w+;\s*PWD\s*=\s*\w+",
    r"(?i)Provider\s*=\s*\w+;\s*Data Source\s*=\s*\w+;\s*User\s+ID\s*=\s*\w+;\s*Password\s*=\s*\w+",
    # SSH keys
    r"(?i)-----BEGIN\s+(?:RSA|DSA|EC|OPENSSH)\s+PRIVATE\s+KEY-----",
    r"(?i)-----BEGIN\s+PRIVATE\s+KEY-----",
    r"(?i)-----BEGIN\s+ENCRYPTED\s+PRIVATE\s+KEY-----",
    r"(?i)-----BEGIN\s+PGP\s+PRIVATE\s+KEY\s+BLOCK-----",
    r"(?i)-----BEGIN\s+CERTIFICATE-----",
    r"(?i)-----BEGIN\s+CERTIFICATE\s+REQUEST-----",
    r"(?i)-----BEGIN\s+PUBLIC\s+KEY-----",
    # Cloud-specific secrets
    r"(?i)AKIA[0-9A-Z]{16}",
    r"(?i)(?:aws_secret|aws_key|aws_token)\s*[=:]\s*['\"]?\w+['\"]?",
    r"(?i)(?:AZURE_|GOOGLE_|GCP_|GCLOUD_|FIREBASE_)\w+\s*=\s*['\"]?\w+['\"]?",
    r"(?i)(?:DO_TOKEN|DIGITALOCEAN_TOKEN|SPACES_KEY|SPACES_SECRET)\s*=\s*\w+",
    r"(?i)(?:LINODE_TOKEN|LINODE_API_KEY)\s*=\s*\w+",
    r"(?i)(?:VULTR_API_KEY|VULTR_TOKEN)\s*=\s*\w+",
    r"(?i)(?:HETZNER_TOKEN|HETZNER_API_KEY)\s*=\s*\w+",
    # Encryption/Signing keys
    r"(?i)(?:HMAC|AES|DES|RSA|SHA|MD5)(?:_KEY|_SECRET|_TOKEN|_PASSPHRASE)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:JWT_SECRET|JWT_KEY|JWT_SIGNING_KEY|JWT_PRIVATE_KEY|JWT_PUBLIC_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:SESSION_SECRET|SESSION_KEY|SESSION_SALT|COOKIE_SECRET|COOKIE_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:ENCRYPTION_KEY|DECRYPTION_KEY|SIGNING_KEY|MASTER_KEY|ROOT_KEY)\s*[=:]\s*['\"]?\w+",
    # Service-specific
    r"(?i)(?:TWILIO_ACCOUNT_SID|TWILIO_AUTH_TOKEN|TWILIO_API_KEY|TWILIO_API_SECRET)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:SENDGRID_API_KEY|SENDGRID_USERNAME|SENDGRID_PASSWORD)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:MAILGUN_API_KEY|MAILGUN_DOMAIN|MAILGUN_SECRET)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:STRIPE_SECRET_KEY|STRIPE_PUBLISHABLE_KEY|STRIPE_WEBHOOK_SECRET)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:PAYPAL_CLIENT_ID|PAYPAL_CLIENT_SECRET|PAYPAL_WEBHOOK_ID)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:BRAINTREE_MERCHANT_ID|BRAINTREE_PUBLIC_KEY|BRAINTREE_PRIVATE_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:SQUARE_APPLICATION_ID|SQUARE_ACCESS_TOKEN|SQUARE_WEBHOOK_SIGNATURE_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:OPENAI_API_KEY|OPENAI_ORG_ID)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:ANTHROPIC_API_KEY|CLAUDE_API_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:GOOGLE_AI_KEY|GEMINI_API_KEY|PALM_API_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:COHERE_API_KEY|HUGGINGFACE_TOKEN|HF_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:REPLICATE_API_TOKEN|STABILITY_API_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:DATADOG_API_KEY|DD_API_KEY|DATADOG_APP_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:NEWRELIC_API_KEY|NEW_RELIC_LICENSE_KEY|NEWRELIC_LICENSE_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:SENTRY_DSN|SENTRY_AUTH_TOKEN|SENTRY_API_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:GRAFANA_API_KEY|GRAFANA_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:ELASTICSEARCH_URL|ELASTICSEARCH_PASSWORD|ELASTIC_APM_SECRET_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:CLOUDFLARE_API_KEY|CLOUDFLARE_API_TOKEN|CLOUDFLARE_ZONE_ID)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:ALGOLIA_APP_ID|ALGOLIA_API_KEY|ALGOLIA_ADMIN_KEY)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:MAPBOX_ACCESS_TOKEN|MAPBOX_SECRET_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GH_TOKEN|GITHUB_PAT)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:GITLAB_TOKEN|GITLAB_PRIVATE_TOKEN|GITLAB_OAUTH_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:BITBUCKET_USERNAME|BITBUCKET_PASSWORD|BITBUCKET_APP_PASSWORD)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:CIRCLE_TOKEN|CIRCLECI_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:TRAVIS_TOKEN|TRAVIS_API_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:CODECOV_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:COVERALLS_REPO_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:SNYK_TOKEN|SNYK_API_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:SONAR_TOKEN|SONARQUBE_TOKEN|SONARCLOUD_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:DOCKER_HUB_TOKEN|DOCKER_HUB_PASSWORD|DOCKER_REGISTRY_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:QUAY_TOKEN|QUAY_API_TOKEN)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:HARBOR_TOKEN|HARBOR_PASSWORD)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:REDIS_URL|REDIS_PASSWORD|REDIS_HOST)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:MONGO_URL|MONGODB_URL|MONGO_URI|MONGODB_URI)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:DATABASE_URL|DB_URL|DB_CONNECTION|DB_PASSWORD)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:RABBITMQ_URL|AMQP_URL|RABBITMQ_PASSWORD)\s*[=:]\s*['\"]?\w+",
    r"(?i)(?:KAFKA_URL|KAFKA_BOOTSTRAP_SERVERS)\s*[=:]\s*['\"]?\w+",
]

# ============================================================================
# 6. MOBILE & IOT ATTACKS (150 patterns)
# ============================================================================
MOBILE_IOT = [
    # Mobile API attacks
    r"(?i)/api/v\d+/auth/(?:login|register|forgot|reset|verify|token|refresh|logout|otp|sms|email)\b",
    r"(?i)/api/v\d+/user/(?:profile|update|delete|password|email|phone|avatar|settings|preferences|notifications|devices)\b",
    r"(?i)/api/v\d+/payment/(?:process|checkout|card|bank|wallet|refund|subscription|plan|invoice|receipt)\b",
    r"(?i)/api/v\d+/upload/(?:image|file|document|video|audio|avatar|attachment)\b",
    r"(?i)/api/v\d+/admin/(?:users|roles|permissions|settings|config|logs|audit|backup|restore|export|import)\b",
    r"(?i)/api/v\d+/internal/\b",
    r"(?i)/api/v\d+/debug/\b",
    r"(?i)/api/v\d+/test/\b",
    r"(?i)/api/v\d+/staging/\b",
    r"(?i)/api/v\d+/dev/\b",
    r"(?i)x-api-version\s*:\s*\w+\b",
    r"(?i)x-app-version\s*:\s*\w+\b",
    r"(?i)x-device-id\s*:\s*\w+\b",
    r"(?i)x-device-type\s*:\s*\w+\b",
    r"(?i)x-platform\s*:\s*\w+\b",
    r"(?i)x-os-version\s*:\s*\w+\b",
    r"(?i)x-build-number\s*:\s*\w+\b",
    r"(?i)x-app-id\s*:\s*\w+\b",
    r"(?i)x-install-id\s*:\s*\w+\b",
    r"(?i)x-push-token\s*:\s*\w+\b",
    # Certificate pinning bypass
    r"(?i)ssl[_-]?(?:verify|check|validation|certificate|cert|pin)\s*[=:]\s*(?:false|0|no|off|disable|none)\b",
    r"(?i)(?:verify[_-]?ssl|check[_-]?ssl|validate[_-]?cert|verify[_-]?cert)\s*[=:]\s*(?:false|0|no|off|disable|none)\b",
    r"(?i)(?:InsecureSkipVerify|TLSSkipVerify|skipSSLVerification|disableSSLVerification)\s*[=:]\s*(?:true|1|yes)\b",
    r"(?i)(?:CURLOPT_SSL_VERIFYPEER|CURLOPT_SSL_VERIFYHOST)\s*[=:,]\s*(?:false|0)\b",
    # IoT / MQTT / CoAP
    r"(?i)mqtt://\w+\b",
    r"(?i)mqtts://\w+\b",
    r"(?i)coap://\w+\b",
    r"(?i)coaps://\w+\b",
    r"(?i)\$SYS/\b",
    r"(?i)\$SYS/broker/\b",
    r"(?i)\$SYS/broker/clients/\b",
    r"(?i)\$SYS/broker/load/\b",
    r"(?i)\$SYS/broker/messages/\b",
    r"(?i)\$SYS/broker/subscriptions/\b",
    r"(?i)\$SYS/broker/uptime\b",
    r"(?i)\$SYS/broker/version\b",
    r"(?i)\+/\+/\+\b",
    r"(?i)#/\b",
    r"(?i)/\+/#\b",
    r"(?i)topic=.*(?:cmd|exec|system|shell|admin|config|password|secret|token|key)\b",
    # Smart home / IoT endpoints
    r"(?i)/api/(?:device|sensor|actuator|gateway|hub|bridge|controller|firmware|update|ota|diagnostic|telemetry|command|status|health|config|register|provision|discover|pair|unpair|reset|reboot|factory-reset)\b",
    r"(?i)X-Device-Token\b",
    r"(?i)X-Device-Key\b",
    r"(?i)X-Device-Secret\b",
    r"(?i)X-Firmware-Version\b",
    r"(?i)X-Hardware-Id\b",
    r"(?i)X-Serial-Number\b",
    # Bluetooth / Zigbee / Z-Wave
    r"(?i)(?:bluetooth|zigbee|z-wave|zwave|thread|matter|homekit|alexa|google-home|smartthings)\s*(?:token|key|secret|password|pin|code)\s*[=:]\s*['\"]?\w+",
    # Industrial / SCADA
    r"(?i)(?:modbus|dnp3|opc-ua|bacnet|profinet|ethercat|canbus|s7comm)\s*://",
    r"(?i)/(?:modbus|dnp3|opc|bacnet|profinet|ethercat|canbus|s7comm)/\b",
    r"(?i)PLC\s*(?:read|write|start|stop|reset|program|upload|download|config|status)\b",
    r"(?i)HMI\s*(?:access|login|config|upload|download|update|firmware)\b",
    r"(?i)SCADA\s*(?:access|login|config|command|status|alarm|event|trend|report)\b",
    r"(?i)RTU\s*(?:address|config|status|firmware|update)\b",
    # Firmware analysis
    r"(?i)(?:binwalk|firmware-mod-kit|firmwalker|fmk|sasquatch|jefferson|ubi_reader)\b",
    r"(?i)(?:\.bin|\.hex|\.srec|\.s19|\.s28|\.s37|\.elf|\.axf|\.uf2|\.dfu|\.img)\b.*(?:firmware|update|flash|ota)\b",
    # Home automation
    r"(?i)/api/(?:hassio|homeassistant|ha|hass)/\b",
    r"(?i)/api/states/\b",
    r"(?i)/api/services/\b",
    r"(?i)/api/events/\b",
    r"(?i)/api/config/\b",
    r"(?i)/api/template/\b",
    r"(?i)/api/history/\b",
    r"(?i)/api/logbook/\b",
    r"(?i)/api/error_log/\b",
    r"(?i)/api/camera_proxy/\b",
    r"(?i)Authorization\s*:\s*Bearer\s+\w+\.\w+\.\w+\b",
    # Camera / streaming
    r"(?i)(?:rtsp|rtmp|hls|dash|mjpeg|onvif)://",
    r"(?i)/onvif/device_service\b",
    r"(?i)/onvif/media_service\b",
    r"(?i)/onvif/ptz_service\b",
    r"(?i)/onvif/event_service\b",
    r"(?i)/cgi-bin/snapshot\.cgi\b",
    r"(?i)/cgi-bin/viewer\.cgi\b",
    r"(?i)/cgi-bin/mjpg/video\.cgi\b",
    r"(?i)/live/(?:ch\d+|cam\d+|stream\d+)\b",
    r"(?i)/video(?:stream|feed|capture)\b",
    r"(?i)/axis-cgi/\b",
    r"(?i)/stw-cgi/\b",
    r"(?i)/ISAPI/\b",
    r"(?i)/SDK/\b",
    r"(?i)/PSIA/\b",
    # Router / Network device attacks
    r"(?i)/cgi-bin/luci\b",
    r"(?i)/cgi-bin/webproc\b",
    r"(?i)/currentsetting\.htm\b",
    r"(?i)/setup\.cgi\b",
    r"(?i)/HNAP1/\b",
    r"(?i)/goform/\b",
    r"(?i)/formLogin\b",
    r"(?i)/userRpm/\b",
    r"(?i)/cgi/\b",
    r"(?i)admin:admin\b",
    r"(?i)admin:password\b",
    r"(?i)admin:1234\b",
    r"(?i)root:root\b",
    r"(?i)admin:admin123\b",
    r"(?i)user:user\b",
    r"(?i)guest:guest\b",
    r"(?i)default:default\b",
    r"(?i)ubnt:ubnt\b",
    r"(?i)pi:raspberry\b",
]

RULES_MEGA_10_MAP = {
    'cve_signatures': CVE_SIGNATURES,
    'waf_bypass': WAF_BYPASS,
    'file_attacks': FILE_ATTACKS,
    'cicd_attacks': CICD_ATTACKS,
    'secrets_detection': SECRETS_DETECTION,
    'mobile_iot': MOBILE_IOT,
}


def get_all_mega10_patterns():
    for category, patterns in RULES_MEGA_10_MAP.items():
        for regex_str in patterns:
            yield (regex_str, category)


def count_mega10_patterns():
    return sum(len(p) for p in RULES_MEGA_10_MAP.values())
