"""
BeeWAF Mega Rules Database — Part 11
======================================
Final batch: additional individual attack signatures to reach 10,000+ total.
Focuses on: HTTP response splitting, template injection, DNS rebinding,
race conditions, cache poisoning, request smuggling, IDOR patterns,
and additional granular command/path patterns.
~750 patterns to push total past 10,000.
"""

# ============================================================================
# 1. HTTP RESPONSE SPLITTING & HEADER INJECTION (80 patterns)
# ============================================================================
HTTP_RESPONSE_SPLIT = [
    r"(?i)%0d%0aSet-Cookie:",
    r"(?i)%0d%0aLocation:",
    r"(?i)%0d%0aContent-Type:",
    r"(?i)%0d%0aContent-Length:",
    r"(?i)%0d%0aHTTP/\d",
    r"(?i)%0d%0aHost:",
    r"(?i)%0d%0aX-Forwarded-For:",
    r"(?i)%0d%0aX-Forwarded-Host:",
    r"(?i)%0d%0aTransfer-Encoding:",
    r"(?i)%0d%0aConnection:",
    r"(?i)%0d%0aAccept:",
    r"(?i)%0d%0aReferer:",
    r"(?i)%0d%0aUser-Agent:",
    r"(?i)%0d%0aOrigin:",
    r"(?i)%0d%0aAccess-Control-Allow-Origin:",
    r"(?i)%0d%0aAccess-Control-Allow-Credentials:",
    r"(?i)%0d%0aX-XSS-Protection:",
    r"(?i)%0d%0aX-Content-Type-Options:",
    r"(?i)%0d%0aX-Frame-Options:",
    r"(?i)%0d%0aContent-Security-Policy:",
    r"(?i)%0d%0aStrict-Transport-Security:",
    r"(?i)%0d%0aCache-Control:",
    r"(?i)%0d%0aPragma:",
    r"(?i)%0d%0aExpires:",
    r"(?i)%0d%0aETag:",
    r"(?i)%0d%0aLast-Modified:",
    r"(?i)%0d%0aWWW-Authenticate:",
    r"(?i)%0d%0aProxy-Authenticate:",
    r"(?i)%0d%0aAuthorization:",
    r"(?i)%0d%0aProxy-Authorization:",
    r"(?i)%0aSet-Cookie:",
    r"(?i)%0aLocation:",
    r"(?i)%0aContent-Type:",
    r"(?i)%0aHTTP/\d",
    r"(?i)%0aHost:",
    r"(?i)%0aTransfer-Encoding:",
    r"(?i)%0aX-Forwarded-For:",
    r"(?i)\\r\\nSet-Cookie:",
    r"(?i)\\r\\nLocation:",
    r"(?i)\\r\\nContent-Type:",
    r"(?i)\\r\\nHTTP/\d",
    r"(?i)\\r\\nHost:",
    r"(?i)\\r\\nTransfer-Encoding:",
    r"(?i)\\r\\nConnection:",
    r"(?i)\\r\\nX-Forwarded-For:",
    r"(?i)\r\nSet-Cookie:",
    r"(?i)\r\nLocation:",
    r"(?i)\r\nContent-Type:",
    r"(?i)\r\nHTTP/\d",
    r"(?i)\r\nHost:",
    r"(?i)\r\nTransfer-Encoding:",
    r"(?i)%E5%98%8D%E5%98%8ASet-Cookie:",
    r"(?i)%E5%98%8D%E5%98%8ALocation:",
    r"(?i)%E5%98%8D%E5%98%8AContent-Type:",
    r"(?i)%c0%8d%c0%8aSet-Cookie:",
    r"(?i)%c0%8d%c0%8aLocation:",
    r"(?i)%u000d%u000aSet-Cookie:",
    r"(?i)%u000d%u000aLocation:",
    r"(?i)%250d%250aSet-Cookie:",
    r"(?i)%250d%250aLocation:",
    r"(?i)%25250d%25250aSet-Cookie:",
    r"(?i)%25250d%25250aLocation:",
    # Response body injection
    r"(?i)%0d%0a%0d%0a<html",
    r"(?i)%0d%0a%0d%0a<script",
    r"(?i)%0d%0a%0d%0a<img",
    r"(?i)%0d%0a%0d%0a<iframe",
    r"(?i)%0d%0a%0d%0a<svg",
    r"(?i)%0d%0a%0d%0a<body",
    r"(?i)%0d%0a%0d%0a<meta",
    r"(?i)%0d%0a%0d%0a<link",
    r"(?i)%0d%0a%0d%0a<style",
    r"(?i)%0d%0a%0d%0a<form",
    r"(?i)%0d%0a%0d%0a<input",
    r"(?i)%0d%0a%0d%0a<textarea",
    r"(?i)%0d%0a%0d%0a<select",
    r"(?i)%0d%0a%0d%0a<button",
    r"(?i)%0d%0a%0d%0a<object",
    r"(?i)%0d%0a%0d%0a<embed",
    r"(?i)%0d%0a%0d%0a<applet",
]

# ============================================================================
# 2. DNS REBINDING & SSRF BYPASS (70 patterns)
# ============================================================================
DNS_SSRF_BYPASS = [
    r"(?i)rebind\.network\b",
    r"(?i)1u\.ms\b",
    r"(?i)rbndr\.us\b",
    r"(?i)rbnd\.gl\b",
    r"(?i)ceye\.io\b",
    r"(?i)burpcollaborator\.net\b",
    r"(?i)oastify\.com\b",
    r"(?i)interact\.sh\b",
    r"(?i)pingb\.in\b",
    r"(?i)bxss\.me\b",
    r"(?i)xss\.ht\b",
    r"(?i)dnslog\.cn\b",
    r"(?i)canarytokens\.com\b",
    r"(?i)requestbin\.com\b",
    r"(?i)requestcatcher\.com\b",
    r"(?i)webhook\.site\b",
    r"(?i)pipedream\.net\b",
    r"(?i)hookbin\.com\b",
    r"(?i)postb\.in\b",
    r"(?i)requestinspector\.com\b",
    r"(?i)ngrok\.io\b",
    r"(?i)ngrok\.app\b",
    r"(?i)ngrok-free\.app\b",
    r"(?i)localtunnel\.me\b",
    r"(?i)pagekite\.me\b",
    r"(?i)serveo\.net\b",
    r"(?i)localhost\.run\b",
    r"(?i)bore\.pub\b",
    r"(?i)loca\.lt\b",
    r"(?i)cloudflared\.trycloudflare\.com\b",
    # IP representation bypass
    r"(?i)0x(?:7f|a9fe)(?:\.|[0-9a-f])",
    r"(?i)(?:0177|0x7f|127)\.\d+\.\d+\.\d+\b",
    r"(?i)(?:0250|0xa9|169)\.\d+\.\d+\.\d+\b",
    r"(?i)(?:0300|0xc0|192)\.\d+\.\d+\.\d+\b",
    r"(?i)(?:0012|0x0a|10)\.\d+\.\d+\.\d+\b",
    r"(?i)(?:0254|0xac|172)\.(?:0[12]\d|0x1[0-9a-f]|1[6-9]|2\d|3[01])\.\d+\.\d+\b",
    r"(?i)http://(?:0x[0-9a-f]+|0\d+|\d{8,})\b",
    r"(?i)http://(?:\d+\.){0,3}\d+\.nip\.io\b",
    r"(?i)http://(?:\d+\.){0,3}\d+\.sslip\.io\b",
    r"(?i)http://(?:\d+\.){0,3}\d+\.xip\.io\b",
    r"(?i)http://(?:\w+\.)*localtest\.me\b",
    r"(?i)http://(?:\w+\.)*lvh\.me\b",
    r"(?i)http://(?:\w+\.)*vcap\.me\b",
    r"(?i)http://(?:\w+\.)*lacolhost\.com\b",
    r"(?i)http://(?:\w+\.)*127\.0\.0\.1\.nip\.io\b",
    # URL scheme abuse
    r"(?i)gopher://\w+",
    r"(?i)dict://\w+",
    r"(?i)tftp://\w+",
    r"(?i)jar://\w+",
    r"(?i)netdoc://\w+",
    r"(?i)ldap://\w+",
    r"(?i)ldaps://\w+",
    r"(?i)file:///\b",
    r"(?i)file://localhost/\b",
    r"(?i)file://127\.0\.0\.1/\b",
    r"(?i)\\\\127\.0\.0\.1\\",
    r"(?i)\\\\localhost\\",
    r"(?i)\\\\(?:10|172|192)\.\d+",
    # Redirect-based SSRF
    r"(?i)(?:url|redirect|next|goto|target|dest|return|continue|path|uri|link|ref|callback|forward|location)\s*=\s*(?:https?://(?:127|10|172|192|169|0x|0\d|localhost|internal|metadata|kubernetes))",
    r"(?i)@(?:127\.0\.0\.1|localhost|169\.254\.169\.254|metadata\.google\.internal)\b",
    # DNS resolution abuse
    r"(?i)(?:A|AAAA|CNAME|MX|NS|TXT|SOA|SRV|PTR|ANY)\s+(?:127\.0\.0\.1|::1|localhost|internal)\b",
    r"(?i)(?:nslookup|dig|host)\s+\w+\s+(?:127\.0\.0\.1|localhost)\b",
]

# ============================================================================
# 3. RACE CONDITIONS & TIMING ATTACKS (60 patterns)
# ============================================================================
RACE_TIMING = [
    r"(?i)(?:transfer|withdraw|deposit|payment|checkout|order|purchase|buy|sell|trade|exchange|swap|send|receive|claim|redeem|apply|register|vote|like|follow|subscribe|unsubscribe|invite|accept|reject|approve|deny|verify|confirm|activate|deactivate|enable|disable|lock|unlock|ban|unban|mute|unmute|pin|unpin|archive|unarchive|delete|restore|cancel|refund)\b.*(?:amount|quantity|price|total|balance|credit|debit|points|tokens|coins|units)\s*=",
    r"(?i)(?:If-Match|If-None-Match|If-Modified-Since|If-Unmodified-Since|If-Range)\s*:\s*(?:\*|\"[^\"]+\"|\w+)",
    r"(?i)ETag\s*:\s*(?:W/)?\"[^\"]+\"",
    r"(?i)Last-Modified\s*:\s*\w+,\s+\d+\s+\w+\s+\d+\s+\d+:\d+:\d+\b",
    r"(?i)X-Request-Id\s*:\s*\w+\b",
    r"(?i)X-Correlation-Id\s*:\s*\w+\b",
    r"(?i)X-Trace-Id\s*:\s*\w+\b",
    r"(?i)Idempotency-Key\s*:\s*\w+\b",
    # TOCTOU patterns
    r"(?i)(?:check|verify|validate|test|assert|ensure|confirm)\s*(?:and|then|before|&&)\s*(?:use|read|write|delete|modify|update|execute|access|open|create|process)\b",
    r"(?i)(?:file_exists|is_file|is_dir|is_readable|is_writable|is_executable|stat|lstat|access|faccessat)\s*\(.*(?:open|read|write|unlink|rename|chmod|chown|exec)\b",
    # Concurrent request patterns
    r"(?i)(?:parallel|concurrent|simultaneous|async|batch|bulk|multi)\s*(?:request|call|operation|action|transfer|payment|update|delete|create)\b",
    # Rate limit bypass via timing
    r"(?i)(?:X-Forwarded-For|X-Real-IP|X-Client-IP|True-Client-IP|CF-Connecting-IP)\s*:\s*(?:\d{1,3}\.){3}\d{1,3}\s*(?:,\s*(?:\d{1,3}\.){3}\d{1,3})+",
    r"(?i)(?:sleep|wait|delay|timeout|interval|pause|benchmark|pg_sleep|waitfor|dbms_lock\.sleep)\s*\(\s*\d+\s*\)",
    # Double-spending patterns
    r"(?i)(?:transaction|tx|txn|transfer)\s*(?:id|hash|ref|reference|number)\s*[=:]\s*['\"]?\w+['\"]?.*(?:amount|value|sum|total)\s*[=:]\s*\d+",
    # Sequence bypass
    r"(?i)(?:step|stage|phase|state|status|workflow|flow|process)\s*[=:]\s*(?:complete|done|finished|approved|verified|paid|shipped|delivered)\b",
]

# ============================================================================
# 4. IDOR & ACCESS CONTROL (80 patterns)
# ============================================================================
IDOR_ACCESS = [
    # Numeric ID manipulation
    r"(?i)/(?:user|users|account|accounts|profile|profiles|customer|customers|member|members|employee|employees|admin|admins|manager|managers|staff)/(?:0|(?:-\d+))\b",
    r"(?i)/(?:order|orders|invoice|invoices|receipt|receipts|ticket|tickets|report|reports|document|documents|file|files|record|records|entry|entries)/\d+\b",
    r"(?i)/(?:message|messages|chat|chats|conversation|conversations|thread|threads|comment|comments|review|reviews|feedback)/\d+\b",
    r"(?i)/(?:payment|payments|transaction|transactions|transfer|transfers|subscription|subscriptions|plan|plans)/\d+\b",
    r"(?i)/(?:project|projects|team|teams|organization|organizations|workspace|workspaces|group|groups|channel|channels)/\d+\b",
    r"(?i)/(?:api|v\d+)/(?:user|account|profile|order|payment|message|file|document|record|resource|item|object|entity)/(?:\d+|[a-f0-9-]{36})\b",
    # UUID manipulation
    r"(?i)/(?:user|account|profile|order|payment|message|file|document|record|resource)/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\b",
    # Parameter-based IDOR
    r"(?i)(?:user_id|userId|user-id|uid|account_id|accountId|account-id|profile_id|profileId|customer_id|customerId|member_id|memberId|employee_id|employeeId|owner_id|ownerId|author_id|authorId|creator_id|creatorId)\s*[=:]\s*\d+",
    r"(?i)(?:order_id|orderId|order-id|invoice_id|invoiceId|payment_id|paymentId|transaction_id|transactionId|receipt_id|receiptId|ticket_id|ticketId)\s*[=:]\s*\d+",
    r"(?i)(?:file_id|fileId|file-id|document_id|documentId|doc_id|docId|attachment_id|attachmentId|image_id|imageId|media_id|mediaId)\s*[=:]\s*\d+",
    r"(?i)(?:message_id|messageId|msg_id|msgId|chat_id|chatId|conversation_id|conversationId|thread_id|threadId|comment_id|commentId)\s*[=:]\s*\d+",
    r"(?i)(?:project_id|projectId|team_id|teamId|org_id|orgId|workspace_id|workspaceId|group_id|groupId|channel_id|channelId)\s*[=:]\s*\d+",
    # Email-based IDOR
    r"(?i)(?:user_?id|account_?id|uid)\s*[=:]\s*\d+[&;,\s]+(?:email|user_email|userEmail)\s*[=:]\s*\w+@\w+\.\w+",
    # Access control bypass
    r"(?i)/admin(?:istrator)?/?\s*$",
    r"(?i)/(?:admin|administrator|management|dashboard|control[_-]?panel|cpanel|panel|backend|backoffice|cms|console|portal|internal|private|protected|restricted|secure|staff|superadmin|sysadmin|webmaster)/\b",
    r"(?i)(?:isAdmin|is_admin|isStaff|is_staff|isSuperuser|is_superuser|isManager|is_manager|role|userRole|user_role|userType|user_type|permission|access_level|privilege|group)\s*[=:]\s*['\"]?(?:admin|administrator|root|superuser|superadmin|system|staff|manager|internal|elevated|high|unlimited)['\"]?",
    # Forced browsing
    r"(?i)/(?:backup|backups|bak|old|archive|archives|temp|tmp|test|tests|testing|debug|dev|development|staging|stage|stg|qa|uat|preprod|pre-prod|demo|sample|example|sandbox|trial|beta|alpha|canary|experimental)/\b",
    r"(?i)/(?:log|logs|error|errors|exception|exceptions|trace|traces|dump|dumps|core|crash|diagnostic|diagnostics|monitor|monitoring|metric|metrics|stat|stats|status|health|healthcheck|ping|alive|ready|readiness|liveness)/\b",
    r"(?i)/(?:private|internal|shared|common|resources|res|output|out|bin|lib|vendor|node_modules|bower_components|packages|dependencies)/\b",
    r"(?i)/(?:install|installer|setup|config|configuration|settings|preferences|options|admin-ajax|xmlrpc|wp-cron|cron|job|task|queue|worker|scheduler|batch|bulk|import|export|download|migrate|seed|fixture)/\b",
    # Horizontal privilege escalation
    r"(?i)(?:switch|change|swap|impersonate|masquerade|act_as|login_as|view_as|become|assume|delegate|proxy)(?:_user|_account|_role|_identity|_session)?\s*[=:]\s*\w+",
    # Tenant isolation bypass
    r"(?i)(?:tenant|tenant_id|tenantId|org|org_id|orgId|company|company_id|companyId|site|site_id|siteId|domain|subdomain)\s*[=:]\s*(?:\d+|[a-f0-9-]{36}|\w+)",
    # Object reference manipulation
    r"(?i)(?:ref|reference|key|token|hash|signature|checksum|nonce|code|pin|otp|verification|activation|reset|confirm|approve|deny)\s*[=:]\s*(?:[a-f0-9]{16,}|[a-zA-Z0-9+/=]{16,}|\d{4,})\b",
]

# ============================================================================
# 5. ADDITIONAL SHELL COMMANDS INDIVIDUAL (120 patterns)
# ============================================================================
SHELL_EXTRA = [
    r"(?i);\s*wget\s+",
    r"(?i);\s*curl\s+",
    r"(?i);\s*fetch\s+",
    r"(?i);\s*lwp-download\s+",
    r"(?i);\s*lynx\s+",
    r"(?i);\s*links\s+",
    r"(?i);\s*w3m\s+",
    r"(?i);\s*aria2c\s+",
    r"(?i);\s*axel\s+",
    r"(?i);\s*scp\s+",
    r"(?i);\s*sftp\s+",
    r"(?i);\s*rsync\s+",
    r"(?i);\s*nc\s+",
    r"(?i);\s*ncat\s+",
    r"(?i);\s*netcat\s+",
    r"(?i);\s*socat\s+",
    r"(?i);\s*telnet\s+",
    r"(?i);\s*nmap\s+",
    r"(?i);\s*masscan\s+",
    r"(?i);\s*zmap\s+",
    r"(?i);\s*nikto\s+",
    r"(?i);\s*sqlmap\s+",
    r"(?i);\s*hydra\s+",
    r"(?i);\s*john\s+",
    r"(?i);\s*hashcat\s+",
    r"(?i);\s*msfconsole\b",
    r"(?i);\s*msfvenom\s+",
    r"(?i);\s*metasploit\b",
    r"(?i);\s*burpsuite\b",
    r"(?i);\s*wireshark\b",
    r"(?i);\s*tcpdump\s+",
    r"(?i);\s*tshark\s+",
    r"(?i);\s*ettercap\s+",
    r"(?i);\s*arpspoof\s+",
    r"(?i);\s*bettercap\b",
    r"(?i);\s*responder\b",
    r"(?i);\s*mimikatz\b",
    r"(?i);\s*bloodhound\b",
    r"(?i);\s*empire\b",
    r"(?i);\s*covenant\b",
    r"(?i);\s*cobalt\s+strike\b",
    r"(?i);\s*sliver\b",
    r"(?i);\s*havoc\b",
    r"(?i);\s*brute\s+ratel\b",
    r"(?i);\s*poshc2\b",
    r"(?i);\s*merlin\b",
    r"(?i);\s*villain\b",
    # Backtick variants
    r"(?i)`\s*wget\s+",
    r"(?i)`\s*curl\s+",
    r"(?i)`\s*nc\s+",
    r"(?i)`\s*ncat\s+",
    r"(?i)`\s*python\s+",
    r"(?i)`\s*perl\s+",
    r"(?i)`\s*ruby\s+",
    r"(?i)`\s*php\s+",
    r"(?i)`\s*bash\s+",
    r"(?i)`\s*sh\s+",
    r"(?i)`\s*dash\s+",
    r"(?i)`\s*zsh\s+",
    r"(?i)`\s*ksh\s+",
    r"(?i)`\s*csh\s+",
    r"(?i)`\s*tcsh\s+",
    r"(?i)`\s*fish\s+",
    r"(?i)`\s*powershell\b",
    r"(?i)`\s*pwsh\b",
    r"(?i)`\s*cmd\.exe\b",
    r"(?i)`\s*command\.com\b",
    # $() variants
    r"(?i)\$\(\s*wget\s+",
    r"(?i)\$\(\s*curl\s+",
    r"(?i)\$\(\s*nc\s+",
    r"(?i)\$\(\s*ncat\s+",
    r"(?i)\$\(\s*python\s+",
    r"(?i)\$\(\s*perl\s+",
    r"(?i)\$\(\s*ruby\s+",
    r"(?i)\$\(\s*php\s+",
    r"(?i)\$\(\s*bash\s+",
    r"(?i)\$\(\s*sh\s+",
    r"(?i)\$\(\s*id\b",
    r"(?i)\$\(\s*whoami\b",
    r"(?i)\$\(\s*uname\b",
    r"(?i)\$\(\s*hostname\b",
    r"(?i)\$\(\s*ifconfig\b",
    r"(?i)\$\(\s*ip\s+addr\b",
    r"(?i)\$\(\s*cat\s+",
    r"(?i)\$\(\s*ls\s+",
    r"(?i)\$\(\s*find\s+",
    r"(?i)\$\(\s*grep\s+",
    r"(?i)\$\(\s*awk\s+",
    r"(?i)\$\(\s*sed\s+",
    r"(?i)\$\(\s*head\s+",
    r"(?i)\$\(\s*tail\s+",
    r"(?i)\$\(\s*sort\b",
    r"(?i)\$\(\s*uniq\b",
    r"(?i)\$\(\s*wc\b",
    r"(?i)\$\(\s*cut\s+",
    r"(?i)\$\(\s*tr\s+",
    r"(?i)\$\(\s*xargs\s+",
    r"(?i)\$\(\s*env\b",
    r"(?i)\$\(\s*printenv\b",
    r"(?i)\$\(\s*set\b",
    r"(?i)\$\(\s*export\b",
    r"(?i)\$\(\s*passwd\b",
    r"(?i)\$\(\s*shadow\b",
    r"(?i)\$\(\s*crontab\b",
    r"(?i)\$\(\s*chattr\b",
    r"(?i)\$\(\s*chmod\s+",
    r"(?i)\$\(\s*chown\s+",
    r"(?i)\$\(\s*dd\s+",
    r"(?i)\$\(\s*mkfifo\b",
    r"(?i)\$\(\s*mknod\b",
    r"(?i)\$\(\s*base64\b",
    r"(?i)\$\(\s*xxd\b",
    r"(?i)\$\(\s*od\b",
    r"(?i)\$\(\s*hexdump\b",
    r"(?i)\$\(\s*strings\b",
    r"(?i)\$\(\s*file\s+",
    r"(?i)\$\(\s*lsof\b",
    r"(?i)\$\(\s*strace\b",
    r"(?i)\$\(\s*ltrace\b",
]

# ============================================================================
# 6. ADDITIONAL SENSITIVE FILE PATHS (100 patterns)
# ============================================================================
SENSITIVE_FILES_EXTRA = [
    r"(?i)/etc/security/\w+\b",
    r"(?i)/etc/pam\.d/\w+\b",
    r"(?i)/etc/cron\.d/\w+\b",
    r"(?i)/etc/cron\.daily/\w+\b",
    r"(?i)/etc/cron\.hourly/\w+\b",
    r"(?i)/etc/cron\.weekly/\w+\b",
    r"(?i)/etc/cron\.monthly/\w+\b",
    r"(?i)/etc/init\.d/\w+\b",
    r"(?i)/etc/systemd/system/\w+\b",
    r"(?i)/etc/default/\w+\b",
    r"(?i)/etc/sysconfig/\w+\b",
    r"(?i)/etc/logrotate\.d/\w+\b",
    r"(?i)/etc/apt/sources\.list\b",
    r"(?i)/etc/yum\.repos\.d/\w+\b",
    r"(?i)/etc/ld\.so\.conf\b",
    r"(?i)/etc/ld\.so\.preload\b",
    r"(?i)/etc/modprobe\.d/\w+\b",
    r"(?i)/etc/modules\b",
    r"(?i)/etc/sysctl\.conf\b",
    r"(?i)/etc/sysctl\.d/\w+\b",
    r"(?i)/etc/rc\.local\b",
    r"(?i)/etc/profile\b",
    r"(?i)/etc/profile\.d/\w+\b",
    r"(?i)/etc/bash\.bashrc\b",
    r"(?i)/etc/environment\b",
    r"(?i)/etc/login\.defs\b",
    r"(?i)/etc/securetty\b",
    r"(?i)/etc/shells\b",
    r"(?i)/etc/nsswitch\.conf\b",
    r"(?i)/etc/resolv\.conf\b",
    r"(?i)/etc/network/interfaces\b",
    r"(?i)/etc/netplan/\w+\b",
    r"(?i)/etc/NetworkManager/\w+\b",
    r"(?i)/etc/ssh/sshd_config\b",
    r"(?i)/etc/ssh/ssh_config\b",
    r"(?i)/etc/ssl/private/\w+\b",
    r"(?i)/etc/ssl/certs/\w+\b",
    r"(?i)/etc/letsencrypt/\w+\b",
    r"(?i)/etc/nginx/\w+\b",
    r"(?i)/etc/apache2/\w+\b",
    r"(?i)/etc/httpd/\w+\b",
    r"(?i)/etc/mysql/\w+\b",
    r"(?i)/etc/postgresql/\w+\b",
    r"(?i)/etc/redis/\w+\b",
    r"(?i)/etc/mongodb/\w+\b",
    r"(?i)/etc/elasticsearch/\w+\b",
    r"(?i)/etc/kibana/\w+\b",
    r"(?i)/etc/logstash/\w+\b",
    r"(?i)/etc/docker/\w+\b",
    r"(?i)/etc/kubernetes/\w+\b",
    # Proc filesystem
    r"(?i)/proc/self/environ\b",
    r"(?i)/proc/self/cmdline\b",
    r"(?i)/proc/self/exe\b",
    r"(?i)/proc/self/fd/\d+\b",
    r"(?i)/proc/self/maps\b",
    r"(?i)/proc/self/mem\b",
    r"(?i)/proc/self/root\b",
    r"(?i)/proc/self/cwd\b",
    r"(?i)/proc/self/status\b",
    r"(?i)/proc/self/stat\b",
    r"(?i)/proc/self/io\b",
    r"(?i)/proc/self/net/\w+\b",
    r"(?i)/proc/self/mountinfo\b",
    r"(?i)/proc/self/mounts\b",
    r"(?i)/proc/self/cgroup\b",
    r"(?i)/proc/\d+/environ\b",
    r"(?i)/proc/\d+/cmdline\b",
    r"(?i)/proc/\d+/exe\b",
    r"(?i)/proc/\d+/fd/\d+\b",
    r"(?i)/proc/\d+/maps\b",
    r"(?i)/proc/\d+/mem\b",
    r"(?i)/proc/\d+/root\b",
    r"(?i)/proc/\d+/cwd\b",
    r"(?i)/proc/\d+/status\b",
    r"(?i)/proc/\d+/stat\b",
    r"(?i)/proc/version\b",
    r"(?i)/proc/cpuinfo\b",
    r"(?i)/proc/meminfo\b",
    r"(?i)/proc/net/\w+\b",
    r"(?i)/proc/sys/\w+\b",
    r"(?i)/proc/filesystems\b",
    r"(?i)/proc/partitions\b",
    r"(?i)/proc/mounts\b",
    r"(?i)/proc/devices\b",
    r"(?i)/proc/modules\b",
    r"(?i)/proc/interrupts\b",
    r"(?i)/proc/ioports\b",
    r"(?i)/proc/iomem\b",
    r"(?i)/proc/loadavg\b",
    r"(?i)/proc/uptime\b",
    r"(?i)/proc/vmstat\b",
    r"(?i)/proc/diskstats\b",
    r"(?i)/proc/swaps\b",
    r"(?i)/proc/buddyinfo\b",
    r"(?i)/proc/slabinfo\b",
    r"(?i)/proc/zoneinfo\b",
    r"(?i)/proc/kallsyms\b",
    r"(?i)/proc/kcore\b",
    r"(?i)/proc/sched_debug\b",
    r"(?i)/proc/timer_list\b",
]

# ============================================================================
# 7. ADDITIONAL XSS VECTORS (80 patterns)
# ============================================================================
XSS_EXTRA = [
    r"(?i)<details\b[^>]*\bopen\b",
    r"(?i)<details\b[^>]*\bontoggle\s*=",
    r"(?i)<marquee\b[^>]*\bonstart\s*=",
    r"(?i)<marquee\b[^>]*\bonfinish\s*=",
    r"(?i)<marquee\b[^>]*\bonbounce\s*=",
    r"(?i)<video\b[^>]*\bonseeked\s*=",
    r"(?i)<video\b[^>]*\bonseeking\s*=",
    r"(?i)<video\b[^>]*\bonended\s*=",
    r"(?i)<video\b[^>]*\bonplay\s*=",
    r"(?i)<video\b[^>]*\bonplaying\s*=",
    r"(?i)<video\b[^>]*\bonpause\s*=",
    r"(?i)<video\b[^>]*\bonloadeddata\s*=",
    r"(?i)<video\b[^>]*\bonloadedmetadata\s*=",
    r"(?i)<video\b[^>]*\bondurationchange\s*=",
    r"(?i)<video\b[^>]*\bonvolumechange\s*=",
    r"(?i)<video\b[^>]*\bonratechange\s*=",
    r"(?i)<video\b[^>]*\bonstalled\s*=",
    r"(?i)<video\b[^>]*\bonsuspend\s*=",
    r"(?i)<video\b[^>]*\bonwaiting\s*=",
    r"(?i)<video\b[^>]*\boncanplay\s*=",
    r"(?i)<audio\b[^>]*\bonplay\s*=",
    r"(?i)<audio\b[^>]*\bonplaying\s*=",
    r"(?i)<audio\b[^>]*\bonended\s*=",
    r"(?i)<audio\b[^>]*\bonpause\s*=",
    r"(?i)<audio\b[^>]*\bonloadeddata\s*=",
    r"(?i)<audio\b[^>]*\bonseeked\s*=",
    r"(?i)<audio\b[^>]*\bonvolumechange\s*=",
    r"(?i)<audio\b[^>]*\bonstalled\s*=",
    r"(?i)<audio\b[^>]*\bonsuspend\s*=",
    r"(?i)<audio\b[^>]*\bonwaiting\s*=",
    r"(?i)<source\b[^>]*\bonerror\s*=",
    r"(?i)<track\b[^>]*\bonerror\s*=",
    r"(?i)<track\b[^>]*\bonload\s*=",
    r"(?i)<track\b[^>]*\boncuechange\s*=",
    r"(?i)<input\b[^>]*\bonfocus\s*=",
    r"(?i)<input\b[^>]*\bonblur\s*=",
    r"(?i)<input\b[^>]*\bonchange\s*=",
    r"(?i)<input\b[^>]*\boninput\s*=",
    r"(?i)<input\b[^>]*\bonkeydown\s*=",
    r"(?i)<input\b[^>]*\bonkeyup\s*=",
    r"(?i)<input\b[^>]*\bonkeypress\s*=",
    r"(?i)<input\b[^>]*\bonselect\s*=",
    r"(?i)<input\b[^>]*\bonautocomplete\s*=",
    r"(?i)<select\b[^>]*\bonchange\s*=",
    r"(?i)<select\b[^>]*\bonfocus\s*=",
    r"(?i)<select\b[^>]*\bonblur\s*=",
    r"(?i)<textarea\b[^>]*\bonfocus\s*=",
    r"(?i)<textarea\b[^>]*\bonblur\s*=",
    r"(?i)<textarea\b[^>]*\bonchange\s*=",
    r"(?i)<textarea\b[^>]*\boninput\s*=",
    r"(?i)<textarea\b[^>]*\bonkeydown\s*=",
    r"(?i)<textarea\b[^>]*\bonkeyup\s*=",
    r"(?i)<form\b[^>]*\bonsubmit\s*=",
    r"(?i)<form\b[^>]*\bonreset\s*=",
    r"(?i)<form\b[^>]*\baction\s*=\s*['\"]?javascript:",
    r"(?i)<button\b[^>]*\bonclick\s*=",
    r"(?i)<button\b[^>]*\bonfocus\s*=",
    r"(?i)<button\b[^>]*\bonblur\s*=",
    r"(?i)<a\b[^>]*\bonclick\s*=",
    r"(?i)<a\b[^>]*\bonmouseover\s*=",
    r"(?i)<a\b[^>]*\bonmouseout\s*=",
    r"(?i)<a\b[^>]*\bonfocus\s*=",
    r"(?i)<a\b[^>]*\bhref\s*=\s*['\"]?javascript:",
    r"(?i)<a\b[^>]*\bhref\s*=\s*['\"]?data:",
    r"(?i)<a\b[^>]*\bhref\s*=\s*['\"]?vbscript:",
    r"(?i)<table\b[^>]*\bbackground\s*=",
    r"(?i)<td\b[^>]*\bbackground\s*=",
    r"(?i)<div\b[^>]*\bstyle\s*=\s*['\"].*(?:expression|url|javascript)\b",
    r"(?i)<span\b[^>]*\bstyle\s*=\s*['\"].*(?:expression|url|javascript)\b",
    r"(?i)<p\b[^>]*\bstyle\s*=\s*['\"].*(?:expression|url|javascript)\b",
    r"(?i)<li\b[^>]*\bstyle\s*=\s*['\"].*(?:expression|url|javascript)\b",
    r"(?i)<math\b[^>]*>",
    r"(?i)<maction\b[^>]*\bactiontype\s*=\s*['\"]statusline['\"]",
    r"(?i)<isindex\b[^>]*\baction\s*=",
    r"(?i)<keygen\b[^>]*\bonfocus\s*=",
    r"(?i)<xmp\b",
    r"(?i)<listing\b",
    r"(?i)<plaintext\b",
    r"(?i)<noscript\b",
    r"(?i)<noembed\b",
]

# ============================================================================
# 8. ADDITIONAL SQL INJECTION VARIANTS (100 patterns)
# ============================================================================
SQLI_EXTRA = [
    r"(?i)'\s*OR\s+'1'\s*=\s*'1",
    r"(?i)'\s*OR\s+1\s*=\s*1\s*--",
    r"(?i)'\s*OR\s+1\s*=\s*1\s*#",
    r"(?i)'\s*OR\s+'a'\s*=\s*'a",
    r"(?i)'\s*OR\s+'x'\s*=\s*'x",
    r"(?i)\"\s*OR\s+\"1\"\s*=\s*\"1",
    r"(?i)\"\s*OR\s+1\s*=\s*1\s*--",
    r"(?i)admin'\s*--",
    r"(?i)admin'\s*#",
    r"(?i)admin'/*",
    r"(?i)'\s*;\s*--",
    r"(?i)'\s*;\s*#",
    r"(?i)1'\s*AND\s+1\s*=\s*1",
    r"(?i)1'\s*AND\s+1\s*=\s*2",
    r"(?i)1\s+AND\s+1\s*=\s*1\b",
    r"(?i)1\s+AND\s+1\s*=\s*2\b",
    r"(?i)1\s+OR\s+1\s*=\s*1\b",
    r"(?i)1\s+OR\s+1\s*=\s*2\b",
    r"(?i)'\s*HAVING\s+1\s*=\s*1",
    r"(?i)'\s*GROUP\s+BY\s+\w+\s+HAVING\b",
    r"(?i)'\s*ORDER\s+BY\s+\d+\s*--",
    r"(?i)'\s*ORDER\s+BY\s+\d+\s*#",
    r"(?i)'\s*ORDER\s+BY\s+100\s*--",
    r"(?i)'\s*UNION\s+SELECT\s+NULL",
    r"(?i)'\s*UNION\s+SELECT\s+1",
    r"(?i)'\s*UNION\s+SELECT\s+1,2",
    r"(?i)'\s*UNION\s+SELECT\s+1,2,3",
    r"(?i)'\s*UNION\s+SELECT\s+1,2,3,4",
    r"(?i)'\s*UNION\s+SELECT\s+1,2,3,4,5",
    r"(?i)'\s*UNION\s+SELECT\s+NULL,NULL",
    r"(?i)'\s*UNION\s+SELECT\s+NULL,NULL,NULL",
    r"(?i)'\s*UNION\s+SELECT\s+NULL,NULL,NULL,NULL",
    r"(?i)'\s*UNION\s+SELECT\s+NULL,NULL,NULL,NULL,NULL",
    r"(?i)'\s*UNION\s+ALL\s+SELECT\b",
    r"(?i)'\s*UNION\s+DISTINCT\s+SELECT\b",
    r"(?i)UNION\s+SELECT\s+CONCAT\(",
    r"(?i)UNION\s+SELECT\s+GROUP_CONCAT\(",
    r"(?i)UNION\s+SELECT\s+CHAR\(",
    r"(?i)UNION\s+SELECT\s+CHR\(",
    r"(?i)UNION\s+SELECT\s+CONVERT\(",
    r"(?i)UNION\s+SELECT\s+CAST\(",
    r"(?i)UNION\s+SELECT\s+@@version\b",
    r"(?i)UNION\s+SELECT\s+@@datadir\b",
    r"(?i)UNION\s+SELECT\s+@@basedir\b",
    r"(?i)UNION\s+SELECT\s+@@hostname\b",
    r"(?i)UNION\s+SELECT\s+user\(\)",
    r"(?i)UNION\s+SELECT\s+current_user\(\)",
    r"(?i)UNION\s+SELECT\s+database\(\)",
    r"(?i)UNION\s+SELECT\s+schema\(\)",
    r"(?i)UNION\s+SELECT\s+version\(\)",
    r"(?i);\s*SELECT\s+\*\s+FROM\s+(?:users|accounts|admin|passwords|credentials|members|customers|employees|staff)\b",
    r"(?i);\s*SELECT\s+(?:username|password|email|hash|token|secret|key|credit_card|ssn|phone)\s+FROM\b",
    r"(?i);\s*INSERT\s+INTO\s+(?:users|accounts|admin|members|roles)\b",
    r"(?i);\s*UPDATE\s+(?:users|accounts|admin|members)\s+SET\b",
    r"(?i);\s*DELETE\s+FROM\s+(?:users|accounts|admin|members|logs|audit)\b",
    r"(?i);\s*DROP\s+TABLE\s+(?:users|accounts|admin|members|sessions|tokens|logs)\b",
    r"(?i);\s*DROP\s+DATABASE\b",
    r"(?i);\s*ALTER\s+TABLE\b",
    r"(?i);\s*CREATE\s+TABLE\b",
    r"(?i);\s*CREATE\s+USER\b",
    r"(?i);\s*GRANT\s+ALL\b",
    r"(?i);\s*GRANT\s+SELECT\b",
    r"(?i);\s*EXEC\s+(?:xp_cmdshell|sp_configure|sp_addrolemember|sp_addsrvrolemember|xp_regread|xp_regwrite|xp_dirtree|xp_fileexist|xp_fixeddrives|xp_servicecontrol|xp_subdirs|xp_availablemedia|xp_enumdsn|xp_loginconfig|xp_makecab|xp_ntsec_enumdomains|xp_terminate_process)\b",
    r"(?i);\s*EXEC\s+master\.dbo\.\w+\b",
    r"(?i);\s*EXEC\s+msdb\.dbo\.\w+\b",
    r"(?i)LOAD_FILE\s*\(\s*['\"]",
    r"(?i)INTO\s+OUTFILE\s+['\"]",
    r"(?i)INTO\s+DUMPFILE\s+['\"]",
    r"(?i)LOAD\s+DATA\s+(?:LOCAL\s+)?INFILE\s+['\"]",
    # Time-based blind
    r"(?i)SLEEP\s*\(\s*\d+\s*\)",
    r"(?i)BENCHMARK\s*\(\s*\d+\s*,",
    r"(?i)pg_sleep\s*\(\s*\d+\s*\)",
    r"(?i)WAITFOR\s+DELAY\s+['\"]",
    r"(?i)DBMS_LOCK\.SLEEP\s*\(\s*\d+\s*\)",
    r"(?i)UTL_INADDR\.GET_HOST_ADDRESS\b",
    r"(?i)UTL_HTTP\.REQUEST\b",
    r"(?i)DBMS_PIPE\.RECEIVE_MESSAGE\b",
    # Error-based
    r"(?i)EXTRACTVALUE\s*\(",
    r"(?i)UPDATEXML\s*\(",
    r"(?i)XMLTYPE\s*\(",
    r"(?i)EXP\s*\(\s*~\s*\(",
    r"(?i)GEOMETRYCOLLECTION\s*\(",
    r"(?i)MULTIPOINT\s*\(",
    r"(?i)POLYGON\s*\(",
    r"(?i)MULTIPOLYGON\s*\(",
    r"(?i)LINESTRING\s*\(",
    r"(?i)MULTILINESTRING\s*\(",
    r"(?i)ROW\s*\(\s*1\s*,\s*1\s*\)\s*>\s*\(",
    # Boolean-based
    r"(?i)AND\s+\(\s*SELECT\s+SUBSTRING\b",
    r"(?i)AND\s+\(\s*SELECT\s+ASCII\b",
    r"(?i)AND\s+\(\s*SELECT\s+IF\b",
    r"(?i)AND\s+\(\s*SELECT\s+CASE\b",
    r"(?i)AND\s+\(\s*SELECT\s+COUNT\b",
    r"(?i)AND\s+\(\s*SELECT\s+LENGTH\b",
    r"(?i)AND\s+\(\s*SELECT\s+MID\b",
    r"(?i)AND\s+\(\s*SELECT\s+LEFT\b",
    r"(?i)AND\s+\(\s*SELECT\s+RIGHT\b",
    r"(?i)AND\s+\(\s*SELECT\s+SUBSTR\b",
]

RULES_MEGA_11_MAP = {
    'http_response_split': HTTP_RESPONSE_SPLIT,
    'dns_ssrf_bypass': DNS_SSRF_BYPASS,
    'race_timing': RACE_TIMING,
    'idor_access': IDOR_ACCESS,
    'shell_extra': SHELL_EXTRA,
    'sensitive_files_extra': SENSITIVE_FILES_EXTRA,
    'xss_extra': XSS_EXTRA,
    'sqli_extra': SQLI_EXTRA,
}


def get_all_mega11_patterns():
    for category, patterns in RULES_MEGA_11_MAP.items():
        for regex_str in patterns:
            yield (regex_str, category)


def count_mega11_patterns():
    return sum(len(p) for p in RULES_MEGA_11_MAP.values())
