"""
BeeWAF v5.0 Mega Rules Database — Part 1
==========================================
~2500 additional signatures covering advanced SQL injection variants,
XSS polyglots, command injection chains, path traversal encodings,
SSRF cloud metadata, XXE/XSLT, SSTI engines, deserialization gadgets,
LDAP/NoSQL/XPath deep, CRLF/smuggling advanced, and file upload bypass.
"""

# ============================================================================
# 1. SQL INJECTION — ADVANCED VARIANTS (300 patterns)
# ============================================================================
SQLI_ADVANCED = [
    # --- UNION-based deep ---
    r"(?i)UNION\s+ALL\s+SELECT\s+NULL",
    r"(?i)UNION\s+SELECT\s+CHAR\s*\(",
    r"(?i)UNION\s+SELECT\s+0x[0-9a-f]+",
    r"(?i)UNION\s+SELECT\s+CONCAT_WS\s*\(",
    r"(?i)UNION\s+SELECT\s+UNHEX\s*\(",
    r"(?i)UNION\s+SELECT\s+LOAD_FILE\s*\(",
    r"(?i)UNION\s+SELECT\s+@@version",
    r"(?i)UNION\s+SELECT\s+@@datadir",
    r"(?i)UNION\s+SELECT\s+@@hostname",
    r"(?i)UNION\s+SELECT\s+@@basedir",
    r"(?i)UNION\s+SELECT\s+user\s*\(\s*\)",
    r"(?i)UNION\s+SELECT\s+database\s*\(\s*\)",
    r"(?i)UNION\s+SELECT\s+schema_name\s+FROM",
    r"(?i)UNION\s+SELECT\s+table_schema\s+FROM",
    r"(?i)UNION\s+SELECT\s+column_name\s+FROM",
    r"(?i)UNION\s+SELECT\s+grantee\s+FROM",
    r"(?i)UNION\s+SELECT\s+privilege_type",
    r"(?i)UNION\s+SELECT\s+REPLACE\s*\(",
    r"(?i)UNION\s+SELECT\s+MID\s*\(",
    r"(?i)UNION\s+SELECT\s+SUBSTR\s*\(",
    r"(?i)UNION\s+SELECT\s+ASCII\s*\(",
    r"(?i)UNION\s+SELECT\s+ORD\s*\(",
    r"(?i)UNION\s+SELECT\s+HEX\s*\(",
    r"(?i)UNION\s+SELECT\s+BIN\s*\(",
    r"(?i)UNION\s+SELECT\s+OCT\s*\(",
    r"(?i)UNION\s+SELECT\s+CONV\s*\(",
    r"(?i)UNION\s+SELECT\s+LPAD\s*\(",
    r"(?i)UNION\s+SELECT\s+RPAD\s*\(",
    r"(?i)UNION\s+SELECT\s+REVERSE\s*\(",
    r"(?i)UNION\s+SELECT\s+SPACE\s*\(",
    # --- Boolean blind advanced ---
    r"(?i)AND\s+\d+\s*=\s*\d+\s*--",
    r"(?i)OR\s+\d+\s*=\s*\d+\s*--",
    r"(?i)AND\s+\(SELECT\s+COUNT\s*\(\*\)\s+FROM",
    r"(?i)AND\s+\(SELECT\s+SUBSTRING",
    r"(?i)AND\s+\(SELECT\s+LENGTH\s*\(",
    r"(?i)AND\s+\(SELECT\s+IF\s*\(",
    r"(?i)AND\s+\(SELECT\s+CASE\s+WHEN",
    r"(?i)AND\s+\(SELECT\s+MID\s*\(",
    r"(?i)AND\s+\(SELECT\s+LEFT\s*\(",
    r"(?i)AND\s+\(SELECT\s+RIGHT\s*\(",
    r"(?i)AND\s+\(SELECT\s+IFNULL\s*\(",
    r"(?i)AND\s+\(SELECT\s+NULLIF\s*\(",
    r"(?i)AND\s+\(SELECT\s+COALESCE\s*\(",
    r"(?i)AND\s+\(SELECT\s+GREATEST\s*\(",
    r"(?i)AND\s+\(SELECT\s+LEAST\s*\(",
    r"(?i)OR\s+\(SELECT\s+COUNT\s*\(\*\)\s+FROM",
    r"(?i)OR\s+\(SELECT\s+SUBSTRING",
    r"(?i)OR\s+\(SELECT\s+LENGTH\s*\(",
    r"(?i)OR\s+\(SELECT\s+ASCII\s*\(",
    r"(?i)OR\s+\(SELECT\s+ORD\s*\(",
    # --- Time-based blind advanced ---
    r"(?i)IF\s*\(\s*\(SELECT\s+.*\)\s*,\s*SLEEP\s*\(",
    r"(?i)IF\s*\(\s*\(SELECT\s+.*\)\s*,\s*BENCHMARK\s*\(",
    r"(?i)CASE\s+WHEN\s+\(SELECT.*\)\s+THEN\s+SLEEP",
    r"(?i)CASE\s+WHEN\s+\(SELECT.*\)\s+THEN\s+BENCHMARK",
    r"(?i)\bWAITFOR\s+DELAY\s+'0:0:\d+'",
    r"(?i)\bWAITFOR\s+TIME\s+'",
    r"(?i)pg_sleep\s*\(\s*\d+\s*\)",
    r"(?i)DBMS_PIPE\.RECEIVE_MESSAGE\s*\(",
    r"(?i)UTL_INADDR\.GET_HOST_ADDRESS\s*\(",
    r"(?i)UTL_HTTP\.REQUEST\s*\(",
    r"(?i)DBMS_LOCK\.SLEEP\s*\(",
    r"(?i)RANDOMBLOB\s*\(\s*\d{6,}",
    r"(?i)LIKE\s*\(\s*'ABCDEFG',\s*UPPER",
    r"(?i)RLIKE\s+SLEEP\s*\(",
    r"(?i)REGEXP\s+SLEEP\s*\(",
    r"(?i)ELT\s*\(\s*\d+\s*,\s*SLEEP\s*\(",
    # --- Error-based advanced ---
    r"(?i)EXTRACTVALUE\s*\(\s*\d+\s*,\s*CONCAT\s*\(",
    r"(?i)UPDATEXML\s*\(\s*\d+\s*,\s*CONCAT\s*\(",
    r"(?i)XMLTYPE\s*\(\s*CHR\s*\(",
    r"(?i)GEOMETRYCOLLECTION\s*\(\s*\(",
    r"(?i)POLYGON\s*\(\s*\(",
    r"(?i)MULTIPOINT\s*\(\s*\(",
    r"(?i)MULTIPOLYGON\s*\(\s*\(",
    r"(?i)LINESTRING\s*\(\s*\(",
    r"(?i)MULTILINESTRING\s*\(\s*\(",
    r"(?i)EXP\s*\(\s*~\s*\(SELECT",
    r"(?i)GTID_SUBSET\s*\(\s*CONCAT\s*\(",
    r"(?i)JSON_KEYS\s*\(\s*\(SELECT",
    r"(?i)ST_LatFromGeoHash\s*\(",
    r"(?i)ST_LongFromGeoHash\s*\(",
    r"(?i)ST_PointFromGeoHash\s*\(",
    # --- Stacked queries ---
    r"(?i);\s*INSERT\s+INTO\s+\w+\s+VALUES",
    r"(?i);\s*UPDATE\s+\w+\s+SET\s+\w+\s*=",
    r"(?i);\s*DELETE\s+FROM\s+\w+\s+WHERE",
    r"(?i);\s*ALTER\s+TABLE\s+\w+\s+ADD",
    r"(?i);\s*ALTER\s+TABLE\s+\w+\s+DROP",
    r"(?i);\s*CREATE\s+TABLE\s+\w+",
    r"(?i);\s*CREATE\s+USER\s+",
    r"(?i);\s*GRANT\s+ALL\s+ON",
    r"(?i);\s*EXEC\s+master\.dbo\.",
    r"(?i);\s*EXEC\s+xp_cmdshell",
    r"(?i);\s*EXEC\s+sp_configure",
    r"(?i);\s*EXEC\s+sp_addextendedproc",
    r"(?i);\s*EXEC\s+sp_oacreate",
    r"(?i);\s*EXEC\s+sp_oamethod",
    r"(?i);\s*DECLARE\s+@\w+\s+\w+",
    r"(?i);\s*SET\s+@\w+\s*=",
    # --- PostgreSQL specific ---
    r"(?i)COPY\s+\w+\s+FROM\s+PROGRAM\s+'",
    r"(?i)CREATE\s+TEMP\s+TABLE\s+\w+\s*\(\s*\w+\s+text\s*\)",
    r"(?i)lo_import\s*\(",
    r"(?i)lo_export\s*\(",
    r"(?i)pg_read_file\s*\(",
    r"(?i)pg_read_binary_file\s*\(",
    r"(?i)pg_ls_dir\s*\(",
    r"(?i)pg_stat_file\s*\(",
    r"(?i)current_setting\s*\(\s*'",
    r"(?i)set_config\s*\(",
    r"(?i)pg_catalog\.pg_proc",
    r"(?i)pg_catalog\.pg_tables",
    r"(?i)pg_catalog\.pg_namespace",
    r"(?i)string_agg\s*\(\s*\w+",
    r"(?i)array_agg\s*\(\s*\w+",
    r"(?i)chr\s*\(\s*\d+\s*\)\s*\|\|",
    r"(?i)\$\$.*\$\$\s*;",
    r"(?i)LANGUAGE\s+plpgsql",
    r"(?i)LANGUAGE\s+plpythonu",
    r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+\w+",
    # --- MySQL specific ---
    r"(?i)LOAD\s+DATA\s+(?:LOCAL\s+)?INFILE\s+'",
    r"(?i)INTO\s+OUTFILE\s+'",
    r"(?i)INTO\s+DUMPFILE\s+'",
    r"(?i)INFORMATION_SCHEMA\.(?:TABLES|COLUMNS|SCHEMATA|PROCESSLIST|USER_PRIVILEGES)",
    r"(?i)INFORMATION_SCHEMA\.(?:ROUTINES|TRIGGERS|VIEWS|KEY_COLUMN_USAGE)",
    r"(?i)mysql\.(?:user|db|host|func|proc)",
    r"(?i)performance_schema\.\w+",
    r"(?i)sys\.(?:version|sys_config|schema_table_statistics)",
    r"(?i)@@(?:version_compile_os|version_comment|version_compile_machine)",
    r"(?i)@@(?:have_ssl|have_openssl|have_symlink|have_query_cache)",
    r"(?i)@@(?:tmpdir|secure_file_priv|general_log_file|slow_query_log_file)",
    r"(?i)@@(?:pid_file|log_error|plugin_dir|slave_load_tmpdir)",
    r"(?i)MAKE_SET\s*\(\s*\d+",
    r"(?i)EXPORT_SET\s*\(",
    r"(?i)NAME_CONST\s*\(",
    r"(?i)BIT_COUNT\s*\(",
    r"(?i)FOUND_ROWS\s*\(",
    r"(?i)ROW_COUNT\s*\(",
    r"(?i)LAST_INSERT_ID\s*\(",
    # --- Oracle specific ---
    r"(?i)SYS\.USER\$",
    r"(?i)ALL_USERS\b",
    r"(?i)ALL_TABLES\b",
    r"(?i)DBA_USERS\b",
    r"(?i)DBA_TABLES\b",
    r"(?i)V\$SESSION\b",
    r"(?i)V\$INSTANCE\b",
    r"(?i)V\$VERSION\b",
    r"(?i)V\$DATABASE\b",
    r"(?i)UTL_FILE\.\w+",
    r"(?i)UTL_SMTP\.\w+",
    r"(?i)DBMS_JAVA\.\w+",
    r"(?i)DBMS_SCHEDULER\.\w+",
    r"(?i)DBMS_XMLQUERY\.\w+",
    r"(?i)DBMS_OUTPUT\.PUT_LINE",
    r"(?i)CTXSYS\.DRITHSX\.SN\b",
    r"(?i)SYS\.OWA_UTIL\.\w+",
    r"(?i)SYS\.DBMS_EXPORT_EXTENSION",
    r"(?i)EXECUTE\s+IMMEDIATE\s+'",
    r"(?i)DBMS_SQL\.EXECUTE",
    # --- MSSQL specific ---
    r"(?i)master\.\.sysdatabases",
    r"(?i)master\.\.sysobjects",
    r"(?i)master\.\.syscolumns",
    r"(?i)master\.\.syslogins",
    r"(?i)master\.\.sysservers",
    r"(?i)msdb\.dbo\.\w+",
    r"(?i)OPENROWSET\s*\(",
    r"(?i)OPENDATASOURCE\s*\(",
    r"(?i)OPENQUERY\s*\(",
    r"(?i)xp_regread\s*\(",
    r"(?i)xp_regwrite\s*\(",
    r"(?i)xp_servicecontrol\s*\(",
    r"(?i)xp_ntsec_enumdomains",
    r"(?i)xp_terminate_process",
    r"(?i)xp_enumgroups",
    r"(?i)xp_loginconfig",
    r"(?i)sp_password\b",
    r"(?i)sp_addlogin\b",
    r"(?i)sp_droplogin\b",
    r"(?i)sp_addsrvrolemember\b",
    r"(?i)sp_helprotect\b",
    r"(?i)fn_my_permissions\b",
    r"(?i)HAS_DBACCESS\s*\(",
    r"(?i)IS_SRVROLEMEMBER\s*\(",
    r"(?i)IS_MEMBER\s*\(",
    r"(?i)SUSER_SNAME\s*\(",
    # --- SQLite specific ---
    r"(?i)sqlite_master\b",
    r"(?i)sqlite_temp_master\b",
    r"(?i)sqlite_version\s*\(",
    r"(?i)ATTACH\s+DATABASE\s+'",
    r"(?i)load_extension\s*\(",
    r"(?i)fts3_tokenizer\s*\(",
    r"(?i)PRAGMA\s+(?:table_info|index_list|database_list|compile_options)",
    r"(?i)PRAGMA\s+(?:foreign_key_list|integrity_check|journal_mode)",
    # --- Obfuscation techniques ---
    r"(?i)/\*!\d{5}\s+SELECT\b",
    r"(?i)/\*!\d{5}\s+UNION\b",
    r"(?i)/\*!\d{5}\s+INSERT\b",
    r"(?i)/\*!\d{5}\s+UPDATE\b",
    r"(?i)/\*!\d{5}\s+DELETE\b",
    r"(?i)/\*!\d{5}\s+DROP\b",
    r"(?i)S%45LECT\b",
    r"(?i)UN%49ON\b",
    r"(?i)SEL%45CT\b",
    r"(?i)UNI%4fN\b",
    r"(?i)%53ELECT\b",
    r"(?i)%55NION\b",
    r"(?i)S\x00E\x00L\x00E\x00C\x00T",
    r"(?i)U\x00N\x00I\x00O\x00N",
    r"(?i)SELECT\s+/\*\*/\s+FROM",
    r"(?i)UNION\s+/\*\*/\s+SELECT",
    r"(?i)SELECT/\*\*//\*\*/FROM",
    r"(?i)UNION/\*\*//\*\*/SELECT",
    r"(?i)SeLeCt\s+FrOm",
    r"(?i)UnIoN\s+SeLeCt",
    r"(?i)0x(?:73656c656374|756e696f6e|64726f70|696e73657274|64656c657465)",
    r"(?i)CHAR\s*\(\s*(?:83|115)\s*\)\s*\+\s*CHAR\s*\(\s*(?:69|101)\s*\)",
    r"(?i)CHR\s*\(\s*(?:83|115)\s*\)\s*\|\|\s*CHR\s*\(\s*(?:69|101)\s*\)",
    r"(?i)CONCAT\s*\(\s*(?:CHAR|CHR)\s*\(\s*\d+\s*\)\s*,",
    r"(?i)GROUP_CONCAT\s*\(\s*(?:table|column|schema)_name",
    r"(?i)LISTAGG\s*\(\s*\w+\s*,\s*'",
    r"(?i)STRING_AGG\s*\(\s*CAST\s*\(",
    r"(?i)XMLAGG\s*\(\s*XMLELEMENT\s*\(",
    # --- Injection through JSON/XML ---
    r"(?i)JSON_EXTRACT\s*\(\s*\(SELECT",
    r"(?i)JSON_OBJECT\s*\(\s*'.*'\s*,\s*\(SELECT",
    r"(?i)JSON_ARRAYAGG\s*\(\s*\(SELECT",
    r"(?i)JSON_TABLE\s*\(\s*'",
    r"(?i)JSON_VALUE\s*\(\s*\(SELECT",
    r"(?i)JSON_SET\s*\(",
    r"(?i)JSON_REPLACE\s*\(",
    r"(?i)JSON_REMOVE\s*\(",
    r"(?i)JSON_MERGE_PATCH\s*\(",
    r"(?i)XMLTYPE\s*\(\s*'<",
    # --- Window functions abuse ---
    r"(?i)ROW_NUMBER\s*\(\s*\)\s+OVER\s*\(",
    r"(?i)RANK\s*\(\s*\)\s+OVER\s*\(",
    r"(?i)DENSE_RANK\s*\(\s*\)\s+OVER\s*\(",
    r"(?i)NTILE\s*\(\s*\d+\s*\)\s+OVER\s*\(",
    r"(?i)LAG\s*\(\s*\w+\s*,\s*\d+\s*\)\s+OVER",
    r"(?i)LEAD\s*\(\s*\w+\s*,\s*\d+\s*\)\s+OVER",
    r"(?i)FIRST_VALUE\s*\(\s*\w+\s*\)\s+OVER",
    r"(?i)LAST_VALUE\s*\(\s*\w+\s*\)\s+OVER",
    # --- Advanced techniques ---
    r"(?i)HANDLER\s+\w+\s+OPEN\b",
    r"(?i)HANDLER\s+\w+\s+READ\b",
    r"(?i)\bALTER\s+SESSION\s+SET\b",
    r"(?i)\bSET\s+GLOBAL\s+",
    r"(?i)\bSET\s+SESSION\s+",
    r"(?i)\bSHOW\s+GRANTS\b",
    r"(?i)\bSHOW\s+CREATE\s+TABLE\b",
    r"(?i)\bSHOW\s+DATABASES\b",
    r"(?i)\bSHOW\s+TABLES\b",
    r"(?i)\bSHOW\s+COLUMNS\b",
    r"(?i)\bSHOW\s+VARIABLES\b",
    r"(?i)\bSHOW\s+STATUS\b",
    r"(?i)\bSHOW\s+PROCESSLIST\b",
    r"(?i)\bSHOW\s+SLAVE\s+STATUS\b",
    r"(?i)\bSHOW\s+MASTER\s+STATUS\b",
    r"(?i)\bSHOW\s+ENGINES\b",
    r"(?i)\bSHOW\s+PLUGINS\b",
    r"(?i)SELECT\s+.*\bFROM\s+pg_shadow\b",
    r"(?i)SELECT\s+.*\bFROM\s+pg_group\b",
    r"(?i)SELECT\s+.*\bFROM\s+pg_authid\b",
    r"(?i)SELECT\s+.*\bFROM\s+pg_roles\b",
    r"(?i)SELECT\s+.*\bFROM\s+pg_user\b",
    r"(?i)PREPARE\s+\w+\s+FROM\s+'",
    r"(?i)EXECUTE\s+\w+\s+USING\b",
    r"(?i)DEALLOCATE\s+\w+",
    # --- NoSQL deep (Mongo/Redis/Cassandra) ---
    r"(?i)\{\s*['\"]?\$(?:where|regex|text|mod|all|size|type|exists|elemMatch|slice)\b",
    r"(?i)\{\s*['\"]?\$(?:pop|pull|push|addToSet|rename|unset|inc|mul|min|max|currentDate)\b",
    r"(?i)\{\s*['\"]?\$(?:lookup|unwind|group|project|match|sort|limit|skip|sample)\b",
    r"(?i)\{\s*['\"]?\$(?:redact|replaceRoot|facet|bucket|bucketAuto|sortByCount)\b",
    r"(?i)\{\s*['\"]?\$(?:geoNear|graphLookup|indexStats|planCacheStats|collStats)\b",
    r"(?i)db\.\w+\.(?:find|findOne|aggregate|mapReduce|distinct|count|explain)\s*\(",
    r"(?i)db\.\w+\.(?:insert|insertOne|insertMany|update|updateOne|updateMany)\s*\(",
    r"(?i)db\.\w+\.(?:delete|deleteOne|deleteMany|remove|drop)\s*\(",
    r"(?i)db\.\w+\.(?:createIndex|dropIndex|reIndex|ensureIndex)\s*\(",
    r"(?i)db\.(?:adminCommand|runCommand|eval|system)\s*\(",
    r"(?i)db\.(?:getSiblingDB|getMongo|getCollection|getCollectionNames)\s*\(",
    r"(?i)db\.(?:dropDatabase|copyDatabase|cloneDatabase|repairDatabase)\s*\(",
    r"(?i)tojson\s*\(",
    r"(?i)printjson\s*\(",
    r"(?i)ObjectId\s*\(",
    r"(?i)BinData\s*\(",
    r"(?i)Timestamp\s*\(",
    r"(?i)ISODate\s*\(",
    r"(?i)NumberLong\s*\(",
    r"(?i)NumberDecimal\s*\(",
    r"(?i)sleep\s*\(\s*\d{3,}\s*\)",
    r"(?i)assert\s*\(\s*false\s*\)",
    # --- Redis injection ---
    r"(?i)\bFLUSHALL\b",
    r"(?i)\bFLUSHDB\b",
    r"(?i)\bCONFIG\s+SET\b",
    r"(?i)\bCONFIG\s+GET\b",
    r"(?i)\bDEBUG\s+SET-ACTIVE-EXPIRE\b",
    r"(?i)\bDEBUG\s+SEGFAULT\b",
    r"(?i)\bCLIENT\s+KILL\b",
    r"(?i)\bCLIENT\s+LIST\b",
    r"(?i)\bSLAVEOF\s+",
    r"(?i)\bREPLICATEOF\s+",
    r"(?i)\bMODULE\s+LOAD\b",
    r"(?i)\bSHUTDOWN\b",
    r"(?i)\bBGSAVE\b",
    r"(?i)\bBGREWRITEAOF\b",
    r"(?i)\bSAVE\b",
    r"(?i)\bLATENCY\s+",
    r"(?i)\bSLOWLOG\s+",
    r"(?i)\bMEMORY\s+DOCTOR\b",
    r"(?i)\bACL\s+(?:SETUSER|DELUSER|CAT|LIST|SAVE|LOAD)\b",
]

# ============================================================================
# 2. XSS — POLYGLOTS & DEEP VARIANTS (250 patterns)
# ============================================================================
XSS_DEEP = [
    # --- Tag-based variants ---
    r"(?i)<\s*script[^>]*\bsrc\s*=",
    r"(?i)<\s*script[^>]*\btype\s*=\s*['\"]?text/javascript",
    r"(?i)<\s*script[^>]*\btype\s*=\s*['\"]?module",
    r"(?i)<\s*script[^>]*\bnomodule\b",
    r"(?i)<\s*script[^>]*\basync\b",
    r"(?i)<\s*script[^>]*\bdefer\b",
    r"(?i)<\s*script[^>]*\bcrossorigin\b",
    r"(?i)<\s*script[^>]*\bintegrity\s*=",
    r"(?i)<\s*link[^>]*\brel\s*=\s*['\"]?(?:import|preload|modulepreload|stylesheet)['\"]?[^>]*\bhref\s*=",
    r"(?i)<\s*meta[^>]*\bhttp-equiv\s*=\s*['\"]?refresh['\"]?[^>]*\bcontent\s*=",
    r"(?i)<\s*meta[^>]*\bhttp-equiv\s*=\s*['\"]?set-cookie",
    r"(?i)<\s*meta[^>]*\bhttp-equiv\s*=\s*['\"]?content-security-policy",
    r"(?i)<\s*base[^>]*\bhref\s*=",
    r"(?i)<\s*embed[^>]*\bsrc\s*=",
    r"(?i)<\s*object[^>]*\bdata\s*=",
    r"(?i)<\s*applet\b",
    r"(?i)<\s*form[^>]*\baction\s*=\s*['\"]?javascript:",
    r"(?i)<\s*isindex\b",
    r"(?i)<\s*bgsound\b",
    r"(?i)<\s*marquee[^>]*\bonstart\s*=",
    r"(?i)<\s*video[^>]*\bonerror\s*=",
    r"(?i)<\s*video[^>]*\bonloadstart\s*=",
    r"(?i)<\s*audio[^>]*\bonerror\s*=",
    r"(?i)<\s*source[^>]*\bonerror\s*=",
    r"(?i)<\s*track[^>]*\bonerror\s*=",
    r"(?i)<\s*input[^>]*\bonfocus\s*=",
    r"(?i)<\s*input[^>]*\bautofocus\b[^>]*\bonfocus\s*=",
    r"(?i)<\s*select[^>]*\bonchange\s*=",
    r"(?i)<\s*textarea[^>]*\bonfocus\s*=",
    r"(?i)<\s*details[^>]*\bontoggle\s*=",
    r"(?i)<\s*details\s+open[^>]*\bontoggle\s*=",
    r"(?i)<\s*dialog[^>]*\bonclose\s*=",
    r"(?i)<\s*fieldset[^>]*\bonfocus\s*=",
    r"(?i)<\s*keygen[^>]*\bonfocus\s*=",
    r"(?i)<\s*math\b.*\bxlink:href\s*=",
    r"(?i)<\s*svg[^>]*\bonload\s*=",
    r"(?i)<\s*svg[^>]*>/\s*<\s*animate\b",
    r"(?i)<\s*svg[^>]*>/\s*<\s*set\b",
    r"(?i)<\s*svg[^>]*>/\s*<\s*animateTransform\b",
    r"(?i)<\s*svg[^>]*>/\s*<\s*use\b[^>]*\bxlink:href\s*=",
    r"(?i)<\s*svg[^>]*>/\s*<\s*foreignObject\b",
    r"(?i)<\s*svg[^>]*>/\s*<\s*a\b[^>]*\bxlink:href\s*=\s*['\"]?javascript:",
    r"(?i)<\s*svg[^>]*\bstyle\s*=\s*['\"]?[^'\"]*animation",
    # --- Event handlers (comprehensive) ---
    r"(?i)\bon(?:abort|afterprint|beforeprint|beforeunload|blur|canplay|canplaythrough)\s*=",
    r"(?i)\bon(?:change|click|contextmenu|copy|cuechange|cut|dblclick)\s*=",
    r"(?i)\bon(?:drag|dragend|dragenter|dragleave|dragover|dragstart|drop)\s*=",
    r"(?i)\bon(?:durationchange|emptied|ended|error|focus|focusin|focusout)\s*=",
    r"(?i)\bon(?:hashchange|input|invalid|keydown|keypress|keyup|load)\s*=",
    r"(?i)\bon(?:loadeddata|loadedmetadata|loadstart|message|mousedown)\s*=",
    r"(?i)\bon(?:mouseenter|mouseleave|mousemove|mouseout|mouseover|mouseup)\s*=",
    r"(?i)\bon(?:mousewheel|offline|online|pagehide|pageshow|paste|pause|play)\s*=",
    r"(?i)\bon(?:playing|popstate|progress|ratechange|reset|resize|scroll)\s*=",
    r"(?i)\bon(?:search|seeked|seeking|select|show|stalled|storage|submit)\s*=",
    r"(?i)\bon(?:suspend|timeupdate|toggle|touchcancel|touchend|touchmove|touchstart)\s*=",
    r"(?i)\bon(?:transitionend|unload|volumechange|waiting|wheel)\s*=",
    r"(?i)\bon(?:animationstart|animationend|animationiteration|animationcancel)\s*=",
    r"(?i)\bon(?:gotpointercapture|lostpointercapture|pointerdown|pointerup)\s*=",
    r"(?i)\bon(?:pointermove|pointerover|pointerout|pointerenter|pointerleave|pointercancel)\s*=",
    r"(?i)\bon(?:beforeinput|compositionstart|compositionupdate|compositionend)\s*=",
    r"(?i)\bon(?:securitypolicyviolation|slotchange|formdata|auxclick)\s*=",
    # --- JavaScript protocol variants ---
    r"(?i)\bjava\s*script\s*:",
    r"(?i)\bj\s*a\s*v\s*a\s*s\s*c\s*r\s*i\s*p\s*t\s*:",
    r"(?i)j&#0*97;vascript:",
    r"(?i)j&#x0*61;vascript:",
    r"(?i)j\u0061vascript:",
    r"(?i)\x6aavascript:",
    r"(?i)\\u006aavascript:",
    r"(?i)data\s*:\s*text/html\s*[;,]",
    r"(?i)data\s*:\s*text/xml\s*[;,]",
    r"(?i)data\s*:\s*application/xhtml\+xml\s*[;,]",
    r"(?i)data\s*:\s*image/svg\+xml\s*[;,]",
    r"(?i)data\s*:\s*application/javascript\s*[;,]",
    r"(?i)data\s*:\s*text/javascript\s*[;,]",
    # --- DOM clobbering ---
    r"(?i)<\s*(?:a|img|form|area)\b[^>]*\bname\s*=\s*['\"]?(?:location|domain|cookie|referrer|URL)['\"]?",
    r"(?i)<\s*(?:a|img|form|area)\b[^>]*\bid\s*=\s*['\"]?(?:location|domain|cookie|referrer|URL)['\"]?",
    r"(?i)document\s*\[\s*['\"]cookie['\"]\s*\]",
    r"(?i)document\s*\.\s*cookie\b",
    r"(?i)document\s*\.\s*domain\b",
    r"(?i)document\s*\.\s*write\s*\(",
    r"(?i)document\s*\.\s*writeln\s*\(",
    r"(?i)document\s*\.\s*execCommand\s*\(",
    r"(?i)document\s*\.\s*implementation\s*\.\s*createHTMLDocument",
    # --- DOM XSS sinks ---
    r"(?i)\.innerHTML\s*=",
    r"(?i)\.outerHTML\s*=",
    r"(?i)\.insertAdjacentHTML\s*\(",
    r"(?i)\.createContextualFragment\s*\(",
    r"(?i)\.srcdoc\s*=",
    r"(?i)DOMParser\s*\(\s*\)\s*\.\s*parseFromString",
    r"(?i)Range\s*\(\s*\)\s*\.\s*createContextualFragment",
    r"(?i)window\s*\.\s*open\s*\(",
    r"(?i)window\s*\.\s*location\s*=",
    r"(?i)window\s*\.\s*location\s*\.\s*href\s*=",
    r"(?i)window\s*\.\s*location\s*\.\s*assign\s*\(",
    r"(?i)window\s*\.\s*location\s*\.\s*replace\s*\(",
    r"(?i)window\s*\.\s*name\s*=",
    r"(?i)window\s*\.\s*postMessage\s*\(",
    r"(?i)\.setAttribute\s*\(\s*['\"]on\w+['\"]",
    r"(?i)\.setAttributeNS\s*\(",
    # --- Template literals ---
    r"(?i)\$\{(?:alert|confirm|prompt|eval|fetch|XMLHttpRequest)",
    r"(?i)`\s*\$\{.*(?:document|window|location|cookie)",
    r"(?i)String\.fromCharCode\s*\(",
    r"(?i)String\.fromCodePoint\s*\(",
    r"(?i)atob\s*\(",
    r"(?i)btoa\s*\(",
    r"(?i)decodeURI(?:Component)?\s*\(",
    r"(?i)encodeURI(?:Component)?\s*\(",
    # --- CSP bypass techniques ---
    r"(?i)<\s*script\b[^>]*\bnonce\s*=",
    r"(?i)<\s*script\b[^>]*\bsrc\s*=\s*['\"]?(?:https?://)?(?:cdn|ajax|apis?)\.",
    r"(?i)require\s*\(\s*['\"]child_process",
    r"(?i)require\s*\(\s*['\"]fs['\"]",
    r"(?i)import\s*\(\s*['\"](?:https?:|data:|blob:)",
    r"(?i)(?:new\s+)?Worker\s*\(\s*['\"]?(?:data:|blob:)",
    r"(?i)(?:new\s+)?SharedWorker\s*\(",
    r"(?i)ServiceWorker\.register\s*\(",
    r"(?i)navigator\.serviceWorker\.register\s*\(",
    # --- Prototype pollution XSS ---
    r"(?i)__proto__\s*[\[.]\s*['\"]?\w+",
    r"(?i)constructor\s*\[\s*['\"]?prototype",
    r"(?i)Object\s*\.\s*(?:assign|create|defineProperty|setPrototypeOf)\s*\(",
    r"(?i)Reflect\s*\.\s*(?:set|defineProperty|setPrototypeOf)\s*\(",
    # --- Angular/React/Vue specific XSS ---
    r"(?i)\{\{.*(?:constructor|__proto__|prototype)\s*\[",
    r"(?i)ng-(?:bind-html|include|init|controller)\s*=",
    r"(?i)v-(?:html|bind|on|text)\s*=\s*['\"]?[^'\"]*(?:\$|eval|alert|Function)",
    r"(?i)dangerouslySetInnerHTML\s*=",
    r"(?i)jsx\s*\(\s*['\"]script",
    r"(?i)\[innerHTML\]\s*=",
    r"(?i)\(click\)\s*=\s*['\"]?[^'\"]*(?:eval|alert|Function)",
    # --- mXSS (mutation XSS) ---
    r"(?i)<\s*noscript\b[^>]*>.*<\s*img\b",
    r"(?i)<\s*noembed\b[^>]*>.*<\s*img\b",
    r"(?i)<\s*noscript\b[^>]*>.*<\s*script\b",
    r"(?i)<\s*style\b[^>]*>.*</\s*style\b[^>]*><\s*script\b",
    r"(?i)<\s*textarea\b[^>]*>.*</\s*textarea\b[^>]*><\s*script\b",
    r"(?i)<\s*title\b[^>]*>.*</\s*title\b[^>]*><\s*script\b",
    r"(?i)<\s*xmp\b[^>]*>.*</\s*xmp\b[^>]*><\s*script\b",
    r"(?i)<\s*iframe\b[^>]*>\s*</\s*iframe\b[^>]*><\s*script\b",
    r"(?i)<\s*math\b[^>]*>.*<\s*mtext\b[^>]*>.*<\s*script\b",
    # --- Encoding-based XSS ---
    r"(?i)%3C\s*script",
    r"(?i)%3C\s*img\b",
    r"(?i)%3C\s*svg\b",
    r"(?i)%3C\s*body\b",
    r"(?i)%3C\s*iframe\b",
    r"(?i)&#x3c;\s*script",
    r"(?i)&#60;\s*script",
    r"(?i)\\u003c\s*script",
    r"(?i)\\x3c\s*script",
    r"(?i)&lt;\s*script",
]

# ============================================================================
# 3. COMMAND INJECTION — DEEP VARIANTS (200 patterns)
# ============================================================================
CMDI_DEEP = [
    # --- Shell metacharacters ---
    r"(?i)[;&|]\s*(?:cat|head|tail|more|less|tac|nl|sort|uniq|wc)\s+",
    r"(?i)[;&|]\s*(?:grep|egrep|fgrep|awk|sed|cut|tr|xargs)\s+",
    r"(?i)[;&|]\s*(?:find|locate|which|whereis|type)\s+",
    r"(?i)[;&|]\s*(?:ls|dir|vdir)\s+(?:-[a-z]+\s+)?/",
    r"(?i)[;&|]\s*(?:cp|mv|rm|mkdir|rmdir|touch|chmod|chown|chgrp)\s+",
    r"(?i)[;&|]\s*(?:ps|top|kill|killall|pkill|pgrep|nohup)\s+",
    r"(?i)[;&|]\s*(?:netstat|ss|ifconfig|ip\s+addr|route|arp)\b",
    r"(?i)[;&|]\s*(?:iptables|nft|firewall-cmd|ufw)\s+",
    r"(?i)[;&|]\s*(?:crontab|at|batch|anacron)\s+",
    r"(?i)[;&|]\s*(?:useradd|userdel|usermod|groupadd|passwd)\s+",
    r"(?i)[;&|]\s*(?:mount|umount|fdisk|mkfs|df|du)\s+",
    r"(?i)[;&|]\s*(?:systemctl|service|init|chkconfig)\s+",
    r"(?i)[;&|]\s*(?:journalctl|dmesg|syslog|logger)\b",
    r"(?i)[;&|]\s*(?:ssh|scp|sftp|rsync|ftp|telnet)\s+",
    r"(?i)[;&|]\s*(?:docker|podman|kubectl|helm|terraform)\s+",
    r"(?i)[;&|]\s*(?:python[23]?|ruby|perl|php|node|java|go)\s+",
    r"(?i)[;&|]\s*(?:gcc|g\+\+|make|cmake|cc)\s+",
    r"(?i)[;&|]\s*(?:tar|gzip|gunzip|bzip2|xz|zip|unzip|7z)\s+",
    r"(?i)[;&|]\s*(?:base64|xxd|hexdump|od|strings)\s+",
    r"(?i)[;&|]\s*(?:openssl|gpg|ssh-keygen|certutil)\s+",
    # --- Backtick and $() variants ---
    r"(?i)`\s*(?:cat|id|whoami|uname|hostname|ifconfig|pwd|ls|dir)\s*`",
    r"(?i)`\s*(?:wget|curl|nc|ncat|socat|bash|sh|zsh|ksh|csh)\b",
    r"(?i)\$\(\s*(?:cat|id|whoami|uname|hostname|ifconfig|pwd|ls|dir)\s",
    r"(?i)\$\(\s*(?:wget|curl|nc|ncat|socat|bash|sh|zsh|ksh|csh)\b",
    r"(?i)\$\(\s*(?:python[23]?|ruby|perl|php|node)\s+",
    r"(?i)\$\(\s*echo\s+[a-zA-Z0-9+/=]+\s*\|\s*base64\s+",
    r"(?i)\$\(\s*printf\s+",
    # --- Pipe chains ---
    r"(?i)\|\s*(?:bash|sh|zsh|ksh|csh|dash|tcsh)\b",
    r"(?i)\|\s*(?:python[23]?|ruby|perl|php|node)\b",
    r"(?i)\|\s*(?:tee|xargs|parallel)\s+",
    r"(?i)\|\s*(?:mail|sendmail|mutt|mailx)\s+",
    r"(?i)\|\s*(?:nc|ncat|netcat|socat)\s+",
    r"(?i)\|\s*(?:dd|xxd|base64|openssl)\s+",
    r"(?i)\|\s*(?:gzip|bzip2|xz)\s*>",
    # --- Reverse shells ---
    r"(?i)bash\s+-(?:i|c)\s+['\"].*(?:/dev/tcp/|/dev/udp/)",
    r"(?i)python[23]?\s+-c\s+['\"]import\s+(?:socket|subprocess|os|pty)",
    r"(?i)ruby\s+-(?:e|rsocket)\s+",
    r"(?i)perl\s+-e\s+['\"].*(?:socket|exec|system)\s*\(",
    r"(?i)php\s+-r\s+['\"].*(?:fsockopen|exec|shell_exec|system|passthru)\s*\(",
    r"(?i)nc\s+-(?:e|c)\s+(?:/bin/(?:sh|bash)|cmd\.exe)",
    r"(?i)ncat\s+(?:--exec|--sh-exec|-e|-c)\s+",
    r"(?i)socat\s+(?:TCP|UDP|EXEC|SYSTEM)\s*:",
    r"(?i)mkfifo\s+/tmp/\w+",
    r"(?i)mknod\s+/tmp/\w+\s+p",
    r"(?i)exec\s+\d+<>/dev/tcp/",
    r"(?i)0<&\d+-\s*;\s*exec\s+\d+<>/dev/tcp/",
    r"(?i)telnet\s+\S+\s+\d+\s*\|\s*/bin/(?:sh|bash)",
    r"(?i)openssl\s+s_client\s+-connect\s+\S+\s*\|\s*/bin/(?:sh|bash)",
    r"(?i)lua\s+-e\s+['\"].*(?:os\.execute|io\.popen)",
    r"(?i)awk\s+['\"]BEGIN\s*\{.*(?:system|cmd|getline)",
    # --- Encoded commands ---
    r"(?i)echo\s+[a-zA-Z0-9+/=]{20,}\s*\|\s*base64\s+-d\s*\|\s*(?:bash|sh)",
    r"(?i)echo\s+[a-zA-Z0-9+/=]{20,}\s*\|\s*base64\s+--decode\s*\|\s*(?:bash|sh)",
    r"(?i)printf\s+['\"]\\x[0-9a-f]+",
    r"(?i)echo\s+-e\s+['\"]\\x[0-9a-f]+",
    r"(?i)echo\s+-ne\s+['\"]\\x[0-9a-f]+",
    r"(?i)\$['\\']\s*\\x[0-9a-f]+",
    r"(?i)xxd\s+-r\s+-p\s*<<<",
    # --- Windows command injection ---
    r"(?i)(?:cmd|command)\.exe\s*/(?:c|k|r)\s+",
    r"(?i)cmd\s*/c\s+(?:dir|type|net|ipconfig|systeminfo|tasklist|schtasks)\b",
    r"(?i)powershell\s+(?:-(?:Command|EncodedCommand|ExecutionPolicy|File|NoProfile|WindowStyle))\b",
    r"(?i)powershell\.exe\s+(?:-(?:ep\s+bypass|nop|sta|enc))\b",
    r"(?i)Start-Process\s+",
    r"(?i)Invoke-Expression\s+",
    r"(?i)Invoke-Command\s+",
    r"(?i)Invoke-WebRequest\s+",
    r"(?i)Invoke-RestMethod\s+",
    r"(?i)New-Object\s+(?:Net\.WebClient|IO\.StreamReader|System\.Diagnostics\.Process)",
    r"(?i)DownloadFile\s*\(",
    r"(?i)DownloadString\s*\(",
    r"(?i)\[System\.Reflection\.Assembly\]::LoadFrom",
    r"(?i)\[System\.Runtime\.InteropServices\.Marshal\]",
    r"(?i)\[Convert\]::FromBase64String",
    r"(?i)Add-MpPreference\s+-ExclusionPath",
    r"(?i)Set-MpPreference\s+-DisableRealtimeMonitoring",
    r"(?i)certutil\s+-urlcache\s+-split\s+-f",
    r"(?i)certutil\s+-decode\b",
    r"(?i)bitsadmin\s+/transfer\b",
    r"(?i)mshta\s+(?:vbscript:|javascript:|http)",
    r"(?i)rundll32\s+(?:javascript:|shell32|url\.dll)",
    r"(?i)regsvr32\s+/s\s+/n\s+/u\s+/i:",
    r"(?i)wmic\s+(?:process|os|useraccount|service|startup)\s+",
    r"(?i)net\s+(?:user|localgroup|share|use|view|session|statistics)\s+",
    r"(?i)net\s+user\s+\w+\s+\w+\s+/add",
    r"(?i)net\s+localgroup\s+administrators\s+\w+\s+/add",
    r"(?i)schtasks\s+/create\s+",
    r"(?i)sc\s+(?:create|config|start|stop|delete|query)\s+",
    r"(?i)reg\s+(?:add|delete|query|save|load|export|import)\s+",
    r"(?i)wevtutil\s+cl\s+",
    r"(?i)vssadmin\s+(?:delete|create|list)\s+shadows",
    r"(?i)bcdedit\s+/set\s+",
    r"(?i)cipher\s+/w:",
    # --- Environment variable access ---
    r"(?i)\$(?:PATH|HOME|USER|SHELL|HOSTNAME|EDITOR|TERM|LANG|PWD)\b",
    r"(?i)\$\{(?:IFS|PATH|HOME|SHELL|USER)\}",
    r"(?i)\$IFS\b",
    r"(?i)\$\{IFS\}",
    r"(?i)export\s+\w+=",
    r"(?i)printenv\b",
    r"(?i)/proc/self/(?:environ|cmdline|status|maps|fd/\d+)",
    r"(?i)/proc/\d+/(?:environ|cmdline|status|maps|exe|root|cwd)",
    # --- Privilege escalation ---
    r"(?i)\bsudo\s+-(?:i|u|s|l|k)\b",
    r"(?i)\bsudo\s+(?:su|bash|sh|python|perl|ruby|php)\b",
    r"(?i)\bsu\s+-\s*$",
    r"(?i)\bsu\s+-\s+root\b",
    r"(?i)\bsu\s+-c\s+",
    r"(?i)chmod\s+[0-7]*[4567][0-7]*\s+",
    r"(?i)chmod\s+[ugo]*\+s\s+",
    r"(?i)chmod\s+4755\s+",
    r"(?i)chattr\s+\+i\s+",
    r"(?i)setcap\s+cap_setuid",
    # --- Container escape ---
    r"(?i)nsenter\s+(?:-t|-m|-u|-i|-n|-p)\s+",
    r"(?i)unshare\s+(?:-U|-m|-n|-p|-i)\b",
    r"(?i)/var/run/docker\.sock",
    r"(?i)docker\s+(?:exec|run|cp|commit|save|load|export|import)\s+",
    r"(?i)docker\s+run\s+.*(?:--privileged|--pid=host|--net=host)",
    r"(?i)docker\s+run\s+.*-v\s+/:/",
    r"(?i)kubectl\s+exec\s+",
    r"(?i)kubectl\s+run\s+.*--(?:command|override)",
    r"(?i)crictl\s+exec\b",
    r"(?i)runc\s+exec\b",
]

# ============================================================================
# 4. PATH TRAVERSAL — ALL ENCODINGS (150 patterns)
# ============================================================================
PATH_TRAVERSAL_DEEP = [
    # --- Standard traversal ---
    r"(?i)\.\.(?:/|\\){1,}(?:etc|var|usr|tmp|opt|home|root|boot|dev|proc|sys)/",
    r"(?i)\.\.(?:/|\\){1,}(?:windows|winnt|system32|syswow64|program\s*files)/",
    r"(?i)\.\.(?:/|\\){1,}(?:inetpub|wwwroot|xampp|wamp|mamp|htdocs|www)/",
    r"(?i)\.\.(?:/|\\){1,}(?:apache|nginx|httpd|tomcat|jboss|wildfly)/",
    # --- Double encoding ---
    r"(?i)%252e%252e(?:%252f|%255c)",
    r"(?i)%252e%252e/",
    r"(?i)%252e%252e\\",
    r"(?i)%2e%2e%2f",
    r"(?i)%2e%2e%5c",
    r"(?i)%%32%65%%32%65%%32%66",
    r"(?i)%25%32%65%25%32%65%25%32%66",
    # --- Unicode/UTF-8 ---
    r"(?i)\xc0\xae\xc0\xae(?:\xc0\xaf|\xc1\x9c)",
    r"(?i)%c0%ae%c0%ae(?:%c0%af|%c1%9c)",
    r"(?i)%u002e%u002e%u002f",
    r"(?i)%u002e%u002e/",
    r"(?i)\u002e\u002e\u002f",
    r"(?i)%uff0e%uff0e%uff0f",
    r"(?i)%e0%80%ae%e0%80%ae%e0%80%af",
    r"(?i)%f0%80%80%ae%f0%80%80%ae%f0%80%80%af",
    # --- Null byte injection ---
    r"(?i)\.\./.*%00",
    r"(?i)\.\.\\.*%00",
    r"(?i)%00\.(?:php|jsp|asp|aspx|cgi|pl)",
    r"(?i)\x00\.(?:php|jsp|asp|aspx|cgi|pl)",
    # --- OS-specific files ---
    r"(?i)/etc/(?:passwd|shadow|group|gshadow|sudoers|hosts|resolv\.conf|hostname|fstab)",
    r"(?i)/etc/(?:crontab|cron\.\w+/|init\.d/|systemd/|logrotate\.d/)",
    r"(?i)/etc/(?:ssh/sshd_config|ssl/|pki/|security/|pam\.d/)",
    r"(?i)/etc/(?:mysql/|postgresql/|redis/|mongod\.conf|php/|nginx/|apache2/|httpd/)",
    r"(?i)/etc/(?:profile|bash\.bashrc|environment|login\.defs|securetty)",
    r"(?i)/etc/(?:xinetd\.d/|inetd\.conf|exports|auto\.master|modprobe\.d/)",
    r"(?i)/var/(?:log/|mail/|spool/|tmp/|cache/|lib/|run/|www/)",
    r"(?i)/var/log/(?:auth\.log|syslog|messages|secure|kern\.log|dmesg|daemon\.log)",
    r"(?i)/var/log/(?:apache2/|nginx/|httpd/|mysql/|postgresql/|tomcat\d*/)",
    r"(?i)/var/log/(?:audit/|wtmp|btmp|lastlog|faillog)",
    r"(?i)/root/\.(?:bash_history|ssh/|gnupg/|mysql_history|psql_history)",
    r"(?i)/home/\w+/\.(?:bash_history|ssh/|gnupg/|profile|bashrc)",
    r"(?i)/home/\w+/\.(?:aws/|docker/|kube/|gitconfig|npmrc|pypirc)",
    r"(?i)/proc/(?:version|cpuinfo|meminfo|mounts|cmdline|config\.gz|modules)",
    r"(?i)/proc/self/(?:status|maps|environ|cmdline|cgroup|mountinfo|net/)",
    r"(?i)/proc/self/fd/\d+",
    r"(?i)/sys/(?:kernel/|class/|devices/|firmware/|fs/|module/)",
    r"(?i)/dev/(?:null|zero|random|urandom|stdin|stdout|stderr|tcp|udp)",
    # --- Windows-specific files ---
    r"(?i)(?:C|D):\\(?:Windows|WINDOWS|WINNT)\\(?:system32|SysWOW64|System)\\",
    r"(?i)(?:C|D):\\(?:Windows|WINDOWS)\\(?:system\.ini|win\.ini|boot\.ini)",
    r"(?i)(?:C|D):\\(?:Windows|WINDOWS)\\(?:repair|debug|Fonts|Help|inf)\\",
    r"(?i)(?:C|D):\\(?:Windows|WINDOWS)\\system32\\config\\(?:SAM|SYSTEM|SECURITY|SOFTWARE|DEFAULT)",
    r"(?i)(?:C|D):\\(?:Windows|WINDOWS)\\system32\\drivers\\etc\\(?:hosts|networks|protocol|services)",
    r"(?i)(?:C|D):\\(?:Users|Documents\s+and\s+Settings)\\",
    r"(?i)(?:C|D):\\(?:inetpub|xampp|wamp|Program\s+Files)\\",
    r"(?i)\\\\(?:localhost|127\.0\.0\.1)\\(?:c\$|admin\$|ipc\$)",
    # --- Application config files ---
    r"(?i)(?:web|app|application)\.(?:config|xml|yml|yaml|json|properties|ini)",
    r"(?i)\.(?:env|env\.local|env\.production|env\.development|env\.staging)",
    r"(?i)(?:wp-config|configuration|settings|config|database)\.(?:php|py|rb|yml|json|xml|ini)",
    r"(?i)(?:appsettings|connectionstrings|machine)\.(?:config|json)",
    r"(?i)(?:docker-compose|Dockerfile|Vagrantfile|Jenkinsfile|Makefile)",
    r"(?i)\.(?:htaccess|htpasswd|htdigest|htgroups)",
    r"(?i)\.(?:gitignore|gitconfig|git-credentials|npmrc|yarnrc|pypirc)",
    r"(?i)\.(?:aws/credentials|aws/config|ssh/id_rsa|ssh/authorized_keys|ssh/known_hosts)",
    r"(?i)\.(?:kube/config|docker/config\.json|terraform\.tfstate)",
    r"(?i)(?:id_rsa|id_dsa|id_ecdsa|id_ed25519)(?:\.pub)?$",
    r"(?i)\.(?:pem|crt|cer|key|pfx|p12|jks|keystore|truststore)$",
    # --- Alternate path separators ---
    r"(?i)\.\.%c0%af",
    r"(?i)\.\.%c1%9c",
    r"(?i)\.\.%c0%9v",
    r"(?i)\.\.%bg%qf",
    r"(?i)\.\./\.\./\.\./\.\./\.\./\.\./\.\./\.\./",
    r"(?i)\.\.\\\.\.\\\.\.\\\.\.\\\.\.\\\.\.\\",
    r"(?i)/\.\.;/\.\.;/\.\.;/",
    r"(?i)\\\.\.\\\.\.\\\.\.\\",
    r"(?i)/\.\./\.\./\.\./\.\./\.\./\.\./\.\./\.\./\.\./\.\./",
    # --- Java/Tomcat specific ---
    r"(?i)WEB-INF/(?:web\.xml|classes/|lib/|applicationContext\.xml)",
    r"(?i)META-INF/(?:MANIFEST\.MF|context\.xml|persistence\.xml)",
    r"(?i)/\.\./\.\./WEB-INF/web\.xml",
    r"(?i)catalina\.(?:policy|properties|out)",
    r"(?i)server\.xml\b",
    r"(?i)context\.xml\b",
    r"(?i)tomcat-users\.xml\b",
    # --- Cloud config files ---
    r"(?i)\.(?:gcloud|config/gcloud|boto|s3cfg)",
    r"(?i)credentials\.(?:json|xml|yml|yaml|ini|properties|conf|cfg)",
    r"(?i)(?:service[-_]?account|gcp[-_]?key|firebase[-_]?key)\.json",
]

# ============================================================================
# 5. SSRF — CLOUD METADATA & INTERNAL (200 patterns)
# ============================================================================
SSRF_DEEP = [
    # --- AWS metadata ---
    r"(?i)169\.254\.169\.254/(?:latest|1\.0|2\.0)/(?:meta-data|user-data|dynamic)",
    r"(?i)169\.254\.169\.254/latest/meta-data/(?:iam|hostname|instance-id|ami-id|instance-type|placement|public-hostname|public-ipv4|local-hostname|local-ipv4|security-groups|network)",
    r"(?i)169\.254\.169\.254/latest/meta-data/iam/security-credentials",
    r"(?i)169\.254\.169\.254/latest/api/token",
    r"(?i)169\.254\.170\.2/v2/credentials",
    r"(?i)169\.254\.169\.254/computeMetadata",
    r"(?i)fd00:ec2::254/",
    # --- GCP metadata ---
    r"(?i)metadata\.google\.internal/computeMetadata/v1/(?:project|instance)",
    r"(?i)metadata\.google\.internal/computeMetadata/v1/instance/(?:service-accounts|hostname|zone|name|network-interfaces|disks|tags|attributes)",
    r"(?i)metadata\.google\.internal/computeMetadata/v1/project/(?:project-id|numeric-project-id|attributes)",
    r"(?i)metadata\.google\.internal/computeMetadata/v1beta1/",
    r"(?i)metadata\.goog/computeMetadata/",
    # --- Azure metadata ---
    r"(?i)169\.254\.169\.254/metadata/(?:instance|attested|identity)",
    r"(?i)169\.254\.169\.254/metadata/instance/(?:compute|network)",
    r"(?i)169\.254\.169\.254/metadata/instance/compute/(?:vmId|name|subscriptionId|resourceGroupName|location|vmSize|osType|platformFaultDomain)",
    r"(?i)169\.254\.169\.254/metadata/identity/oauth2/token",
    # --- DigitalOcean ---
    r"(?i)169\.254\.169\.254/metadata/v1\.json",
    r"(?i)169\.254\.169\.254/metadata/v1/(?:hostname|id|region|interfaces|dns|floating_ip|tags|features|user-data)",
    # --- Oracle Cloud ---
    r"(?i)169\.254\.169\.254/opc/v[12]/(?:instance|vnics|identity)",
    # --- Alibaba Cloud ---
    r"(?i)100\.100\.100\.200/latest/meta-data/",
    r"(?i)100\.100\.100\.200/latest/(?:user-data|meta-data/instance-id|meta-data/hostname)",
    # --- Kubernetes ---
    r"(?i)https?://kubernetes\.default\.svc",
    r"(?i)/api/v1/(?:namespaces|pods|services|secrets|configmaps|nodes|endpoints|events|persistentvolumes)",
    r"(?i)/api/v1/namespaces/\w+/(?:pods|services|secrets|configmaps|endpoints|deployments|replicasets)",
    r"(?i)/apis/(?:apps/v1|batch/v1|extensions/v1beta1|networking\.k8s\.io)",
    r"(?i)/var/run/secrets/kubernetes\.io/serviceaccount/(?:token|ca\.crt|namespace)",
    r"(?i)kube-system\b",
    r"(?i)kube-proxy\b",
    r"(?i)etcd-main\b",
    r"(?i)KUBERNETES_SERVICE_HOST",
    # --- Docker metadata ---
    r"(?i)/var/run/docker\.sock",
    r"(?i)/v[\d.]+/(?:containers|images|networks|volumes|info|version)",
    r"(?i)/v[\d.]+/containers/\w+/(?:json|start|stop|kill|exec|logs|attach)",
    r"(?i)http://docker(?:host)?(?::\d+)?/",
    # --- Internal services ---
    r"(?i)(?:consul|etcd|vault|nomad)\.service\.consul",
    r"(?i)localhost:\d{4,5}/",
    r"(?i)127\.0\.0\.1:\d{4,5}/",
    r"(?i)0\.0\.0\.0:\d{4,5}/",
    r"(?i)\[::1\]:\d{4,5}/",
    r"(?i)http://(?:10|172\.(?:1[6-9]|2\d|3[01])|192\.168)\.\d+\.\d+:\d+/",
    r"(?i)(?:redis|memcached|mysql|postgres|mongo|elasticsearch|rabbitmq|kafka|zookeeper)://",
    r"(?i)amqp://",
    r"(?i)ldap://(?:127|10|172|192\.168)\.",
    # --- IP obfuscation ---
    r"(?i)https?://(?:0x[0-9a-f]+|0[0-7]+|\d{8,10})/",
    r"(?i)https?://(?:\d+\.){0,3}\d+\.\d+/",
    r"(?i)https?://(?:0x[0-9a-f]+\.){3}0x[0-9a-f]+/",
    r"(?i)https?://(?:0[0-7]+\.){3}0[0-7]+/",
    r"(?i)https?://\[(?:0{0,4}:){1,7}(?:0{0,4}:)?1\]/",
    r"(?i)https?://\[::\]:\d+/",
    r"(?i)https?://0/",
    r"(?i)https?://①②⑦",
    # --- Protocol handlers ---
    r"(?i)gopher://\d+\.\d+\.\d+\.\d+",
    r"(?i)dict://\d+\.\d+\.\d+\.\d+",
    r"(?i)sftp://\d+\.\d+\.\d+\.\d+",
    r"(?i)tftp://\d+\.\d+\.\d+\.\d+",
    r"(?i)netdoc://",
    r"(?i)phar://",
    r"(?i)php://(?:filter|input|stdin|fd|memory|temp|data|glob|expect)",
    r"(?i)zip://",
    r"(?i)compress\.(?:zlib|bzip2)://",
    r"(?i)data://text/plain;base64,",
    r"(?i)jar:https?://",
    r"(?i)jar:file://",
    r"(?i)expect://",
    # --- DNS rebinding ---
    r"(?i)\.burpcollaborator\.net\b",
    r"(?i)\.oastify\.com\b",
    r"(?i)\.interact\.sh\b",
    r"(?i)\.canarytokens\.com\b",
    r"(?i)\.pipedream\.net\b",
    r"(?i)\.webhook\.site\b",
    r"(?i)\.requestbin\.(?:net|com)\b",
    r"(?i)\.ngrok\.io\b",
    r"(?i)\.serveo\.net\b",
    r"(?i)\.localtunnel\.me\b",
    r"(?i)\.nip\.io\b",
    r"(?i)\.xip\.io\b",
    r"(?i)\.sslip\.io\b",
    r"(?i)\.1u\.ms\b",
    r"(?i)\.ceye\.io\b",
    r"(?i)\.dnslog\.cn\b",
    r"(?i)\.bxss\.me\b",
    # --- URL parser confusion ---
    r"(?i)https?://[^/]*@\d+\.\d+\.\d+\.\d+",
    r"(?i)https?://\w+:\w+@(?:127|10|172|192\.168)\.",
    r"(?i)https?://[^/]*#@(?:127|10|172|192\.168)\.",
    r"(?i)https?://(?:127|10|172|192\.168)\.[^/]*%(?:00|0d|0a|20)",
    r"(?i)\\\\(?:127|10|172|192\.168)\.\d+\.\d+\.\d+\\",
    r"(?i)//(?:127|10|172|192\.168)\.\d+\.\d+\.\d+/",
]

# ============================================================================
# 6. XXE & XSLT INJECTION (100 patterns)
# ============================================================================
XXE_XSLT_DEEP = [
    # --- XXE variants ---
    r"(?i)<!DOCTYPE\s+\w+\s+\[\s*<!ENTITY\s+",
    r"(?i)<!DOCTYPE\s+\w+\s+SYSTEM\s+['\"]",
    r"(?i)<!DOCTYPE\s+\w+\s+PUBLIC\s+['\"]",
    r"(?i)<!ENTITY\s+\w+\s+SYSTEM\s+['\"](?:file|http|https|ftp|php|data|expect|jar|netdoc)://",
    r"(?i)<!ENTITY\s+%\s+\w+\s+SYSTEM\s+['\"]",
    r"(?i)<!ENTITY\s+%\s+\w+\s+PUBLIC\s+['\"]",
    r"(?i)<!ENTITY\s+\w+\s+['\"](?:&#x[0-9a-f]+;)+['\"]",
    r"(?i)%\w+;\s*%\w+;",
    r"(?i)<!ELEMENT\s+\w+\s+ANY\s*>",
    r"(?i)<!ATTLIST\s+\w+\s+\w+\s+CDATA\s+",
    r"(?i)SYSTEM\s+['\"](?:file|http|ftp|php|data|expect|gopher|jar)://",
    r"(?i)PUBLIC\s+['\"][^'\"]*['\"]\\s+['\"](?:http|ftp)://",
    r"(?i)<!NOTATION\s+",
    r"(?i)xml-stylesheet\s+.*\bhref\s*=\s*['\"]",
    r"(?i)<\?xml[^>]*\bencoding\s*=\s*['\"]UTF-7",
    r"(?i)xmlns(?::\w+)?\s*=\s*['\"](?:http|file|data|jar|php)://",
    # --- Blind XXE ---
    r"(?i)<!ENTITY\s+%\s+\w+\s+SYSTEM\s+['\"]http://\d+\.\d+\.\d+\.\d+",
    r"(?i)<!ENTITY\s+%\s+\w+\s+['\"]<!ENTITY\s+&#x25;",
    r"(?i)<!ENTITY\s+%\s+\w+\s+['\"]<!ENTITY\s+%25;",
    r"(?i)<!ENTITY\s+\w+\s+SYSTEM\s+['\"]php://filter",
    r"(?i)<!ENTITY\s+\w+\s+SYSTEM\s+['\"]expect://",
    r"(?i)<!ENTITY\s+\w+\s+SYSTEM\s+['\"]data://text/plain;base64,",
    r"(?i)<!ENTITY\s+\w+\s+SYSTEM\s+['\"]jar:",
    r"(?i)<!ENTITY\s+\w+\s+SYSTEM\s+['\"]netdoc:",
    # --- XSLT injection ---
    r"(?i)<xsl:stylesheet\b",
    r"(?i)<xsl:transform\b",
    r"(?i)<xsl:(?:import|include)\s+href\s*=\s*['\"]",
    r"(?i)<xsl:(?:value-of|copy-of|for-each|if|choose|when|otherwise)\b",
    r"(?i)<xsl:variable\b[^>]*\bselect\s*=",
    r"(?i)<xsl:param\b[^>]*\bselect\s*=",
    r"(?i)<xsl:output\b[^>]*\bmethod\s*=",
    r"(?i)document\s*\(\s*['\"](?:file|http|ftp)://",
    r"(?i)xsl:(?:script|extension-element-prefixes|use-attribute-sets)",
    r"(?i)msxml:(?:script|using)\b",
    r"(?i)saxon:(?:evaluate|serialize|parse|expression)\b",
    r"(?i)xalan:(?:component|script)\b",
    r"(?i)libxslt\.(?:register|set)_element\b",
    r"(?i)exslt:(?:node-set|object-type|tokenize)\b",
    r"(?i)system-property\s*\(\s*['\"]xsl:",
    r"(?i)unparsed-entity-uri\s*\(",
    r"(?i)function-available\s*\(\s*['\"](?:document|system-property|generate-id)",
    # --- XML bombs (billion laughs) ---
    r"(?i)<!ENTITY\s+\w+\s+['\"](?:&\w+;){2,}['\"]",
    r"(?i)<!ENTITY\s+lol\d+\s+",
    r"(?i)<!ENTITY\s+a\s+['\"](?:&b;)+['\"]",
    r"(?i)<!ENTITY\s+\w{1,3}\s+['\"](?:&\w{1,3};){5,}['\"]",
    # --- SVG-based XXE ---
    r"(?i)<svg[^>]*>.*<!ENTITY",
    r"(?i)<svg[^>]*>.*<!DOCTYPE",
    r"(?i)<svg[^>]*>.*SYSTEM\s+['\"]file://",
    # --- SOAP XXE ---
    r"(?i)<soap:(?:Envelope|Body|Header)\b[^>]*>.*<!ENTITY",
    r"(?i)<(?:soap|soapenv):(?:Envelope|Body)[^>]*>.*SYSTEM\s+['\"]",
    # --- JSON-to-XML XXE ---
    r"(?i)Content-Type:.*application/xml.*<!ENTITY",
    r"(?i)Content-Type:.*text/xml.*<!ENTITY",
]

# ============================================================================
# 7. SSTI — ALL TEMPLATE ENGINES (150 patterns)
# ============================================================================
SSTI_DEEP = [
    # --- Jinja2/Python ---
    r"(?i)\{\{\s*(?:config|self|request|lipsum|cycler|joiner|namespace|url_for)\b",
    r"(?i)\{\{\s*(?:range|dict|chr|ord|int|float|str|list|tuple|set|type)\s*\(",
    r"(?i)\{\{\s*['\"].*['\"]\.(?:__class__|__mro__|__subclasses__|__init__|__globals__|__builtins__|__import__)",
    r"(?i)\{\{.*__(?:class|mro|subclasses|init|globals|builtins|import)__",
    r"(?i)\{\{.*\.__class__\.__mro__\[\d+\]\.__subclasses__\(\)",
    r"(?i)\{\{.*\.__class__\.__bases__\[\d+\]\.__subclasses__\(\)",
    r"(?i)\{\{.*\.__init__\.__globals__\[",
    r"(?i)\{\{.*\.__builtins__\[",
    r"(?i)\{\{.*\.__import__\(['\"]os['\"]\)",
    r"(?i)\{\{.*\.__import__\(['\"]subprocess['\"]\)",
    r"(?i)\{\{.*\.popen\s*\(",
    r"(?i)\{\{.*\.read\s*\(\s*\)",
    r"(?i)\{%\s*(?:if|for|block|extends|include|import|from|set|macro|call|filter|raw)\b",
    r"(?i)\{%\s*import\s+['\"]os['\"]\s*%\}",
    r"(?i)\{%\s*set\s+\w+\s*=\s*(?:config|request|cycler|joiner|namespace)\b",
    # --- Twig (PHP) ---
    r"(?i)\{\{\s*(?:_self|_context|_charset|app)\b",
    r"(?i)\{\{\s*['\"]['\"]\.(?:getClass|forName|getMethod|invoke)\b",
    r"(?i)\{\{\s*(?:constant|include|source|template_from_string)\s*\(",
    r"(?i)\{\{.*\|(?:e|escape|raw|filter|map|sort|reduce|column|batch)\b",
    r"(?i)\{\{.*\bgetenv\s*\(",
    r"(?i)\{\{.*\bpassthru\s*\(",
    r"(?i)\{\{.*\bsystem\s*\(",
    r"(?i)\{\{.*\bexec\s*\(",
    r"(?i)\{\{.*\bshell_exec\s*\(",
    r"(?i)\{\{.*\bpopen\s*\(",
    r"(?i)\{\{.*\bproc_open\s*\(",
    # --- Freemarker (Java) ---
    r"(?i)<#(?:assign|import|include|setting|attempt|recover|function|macro|list|if)\b",
    r"(?i)\$\{['\"]freemarker\.template\.utility\.Execute['\"]",
    r"(?i)\$\{['\"]freemarker\.template\.utility\.ObjectConstructor['\"]",
    r"(?i)\$\{['\"]freemarker\.template\.utility\.JythonRuntime['\"]",
    r"(?i)freemarker\.core\.TemplateClassResolver",
    r"(?i)<#assign\s+\w+\s*=\s*['\"]freemarker",
    r"(?i)\$\{.*\.getClass\(\)\.forName\(",
    r"(?i)\$\{.*\.getRuntime\(\)\.exec\(",
    r"(?i)\$\{.*\.class\.forName\(",
    r"(?i)\$\{.*\.newInstance\(\)",
    r"(?i)new\s*\(\s*['\"]freemarker\.template\.utility\.\w+['\"]",
    r"(?i)\[\"freemarker\.template\.utility\.\w+\"\]",
    # --- Velocity (Java) ---
    r"(?i)#set\s*\(\s*\$\w+\s*=\s*",
    r"(?i)#foreach\s*\(\s*\$\w+\s+in\b",
    r"(?i)#if\s*\(\s*\$\w+",
    r"(?i)#include\s*\(",
    r"(?i)#parse\s*\(",
    r"(?i)\$class\.forName\s*\(",
    r"(?i)\$class\.inspect\b",
    r"(?i)\$class\.type\b",
    r"(?i)\$\w+\.getClass\(\)\.forName\(",
    r"(?i)\$\w+\.class\.forName\(",
    r"(?i)\$\w+\.exec\(",
    # --- ERB (Ruby) ---
    r"(?i)<%=?\s*(?:system|exec|spawn|fork|popen|open|IO\.popen)\s*\(",
    r"(?i)<%=?\s*`[^`]+`\s*%>",
    r"(?i)<%=?\s*(?:Kernel|Process|Open3|PTY)\.\w+\s*\(",
    r"(?i)<%=?\s*(?:File|Dir|IO)\.(?:read|write|open|delete|rename)\s*\(",
    r"(?i)<%=?\s*(?:require|load|eval|instance_eval|class_eval|module_eval)\s*\(",
    r"(?i)<%=?\s*(?:send|public_send|__send__)\s*\(",
    r"(?i)<%=?\s*(?:ObjectSpace|GC|Binding)\.\w+",
    # --- Smarty (PHP) ---
    r"(?i)\{(?:php|literal|capture|include|insert|if|foreach|for|while|function|block)\b",
    r"(?i)\{\$smarty\.(?:server|session|cookies|request|now|const|config|version|template)\}",
    r"(?i)\{(?:system|exec|passthru|shell_exec|popen|proc_open|pcntl_exec)\s*\(",
    r"(?i)\{\$\w+\|(?:system|exec|passthru|shell_exec|popen)\b",
    r"(?i)\{Smarty_Internal_Write_File::writeFile\b",
    # --- Pebble (Java) ---
    r"(?i)\{\{\s*['\"]['\"]\.class\.forName\(",
    r"(?i)\{\{\s*beans\.get\(['\"]",
    r"(?i)\{\{\s*\w+\.getClass\(\)\.forName\(",
    r"(?i)\{\%\s*set\s+\w+\s*=\s*beans\.get\(",
    # --- Thymeleaf (Java) ---
    r"(?i)th:(?:text|utext|attr|attrappend|attrprepend|each|if|unless|switch|case|with|remove|insert|replace|include|fragment)\s*=",
    r"(?i)th:(?:text|utext)\s*=\s*['\"]?\$\{.*T\(java\.lang\.\w+\)",
    r"(?i)__\$\{.*T\(java\.lang\.Runtime\).*\}__",
    r"(?i)__\$\{.*new\s+ProcessBuilder\b.*\}__",
    r"(?i)\$\{T\(java\.lang\.Runtime\)\.getRuntime\(\)\.exec\(",
    r"(?i)\$\{T\(java\.lang\.ProcessBuilder\)",
    r"(?i)\$\{T\(org\.springframework",
    # --- Handlebars/Mustache ---
    r"(?i)\{\{\{.*\}\}\}",
    r"(?i)\{\{#(?:with|each|if|unless|helper|lookup)\b",
    r"(?i)\{\{>\s*(?:constructor|__proto__|prototype)\b",
    r"(?i)\{\{.*(?:constructor\.constructor|Function)\s*\(",
    r"(?i)\{\{lookup\s+this\s+",
    r"(?i)\{\{#with\s+['\"]constructor",
    # --- EL (Expression Language - Java) ---
    r"(?i)\$\{\s*(?:applicationScope|sessionScope|requestScope|pageScope|pageContext)\b",
    r"(?i)\$\{\s*Runtime\.getRuntime\(\)\.exec\(",
    r"(?i)\$\{\s*\w+\.class\.forName\(",
    r"(?i)\$\{\s*\w+\[.class.forName\(.\)",
    r"(?i)#\{.*\.class\.forName\(",
    r"(?i)#\{.*Runtime\.getRuntime\(\)",
    # --- Mako (Python) ---
    r"(?i)<\s*%\s*(?:def|block|text|include|inherit|namespace|page)\b",
    r"(?i)\$\{.*(?:os\.popen|subprocess|__import__|eval|exec|compile)\s*\(",
    r"(?i)<\s*%\s*import\s+os\b",
    r"(?i)<\s*%\s*from\s+subprocess\s+import\b",
    # --- Nunjucks ---
    r"(?i)\{\{.*(?:range|constructor)\s*\(",
    r"(?i)\{\{.*\.constructor\s*\(\s*['\"]return\s+this",
    r"(?i)\{%\s*(?:asyncEach|asyncAll|call|caller|raw|verbatim)\b",
]

# ============================================================================
# 8. DESERIALIZATION GADGETS — ALL LANGUAGES (200 patterns)
# ============================================================================
DESER_DEEP = [
    # --- Java ---
    r"(?i)(?:rO0AB|aced0005|H4sIAAAA|AAAAAA)",
    r"(?i)java\.(?:lang|util|io|net|rmi|beans)\.\w+",
    r"(?i)javax\.(?:management|naming|script|xml)\.\w+",
    r"(?i)sun\.(?:misc|reflect|rmi)\.\w+",
    r"(?i)org\.apache\.commons\.(?:collections|beanutils|lang|io|codec|fileupload|logging)\b",
    r"(?i)org\.apache\.commons\.collections\d?\.(?:Transformer|functors|comparators|keyvalue|map)\b",
    r"(?i)org\.apache\.commons\.collections\d?\.functors\.(?:InvokerTransformer|InstantiateTransformer|ChainedTransformer|ConstantTransformer|ClosureTransformer|TransformerClosure)",
    r"(?i)org\.springframework\.(?:beans|context|core|web|aop|jndi)\.\w+",
    r"(?i)com\.sun\.(?:jndi|rowset|org\.apache|xml)\.\w+",
    r"(?i)com\.mchange\.v2\.c3p0\b",
    r"(?i)org\.codehaus\.groovy\.runtime\b",
    r"(?i)org\.hibernate\.\w+",
    r"(?i)org\.jboss\.\w+",
    r"(?i)com\.alibaba\.fastjson\b",
    r"(?i)com\.fasterxml\.jackson\b",
    r"(?i)net\.sf\.json\.JSONObject\b",
    r"(?i)org\.json\.JSONObject\b",
    r"(?i)bsh\.Interpreter\b",
    r"(?i)clojure\.core\$eval\b",
    r"(?i)org\.python\.core\b",
    r"(?i)org\.mozilla\.javascript\b",
    r"(?i)javassist\.\w+",
    r"(?i)ysoserial\b",
    r"(?i)marshalsec\b",
    r"(?i)JRMPClient\b",
    r"(?i)JRMPListener\b",
    r"(?i)CommonsCollections[1-7]\b",
    r"(?i)CommonsBeanutils\d?\b",
    r"(?i)Spring[12]\b",
    r"(?i)Groovy\d?\b",
    r"(?i)Hibernate[12]\b",
    r"(?i)Jdk7u21\b",
    r"(?i)ROME\b.*chain",
    r"(?i)BeanShell\d?\b",
    r"(?i)C3P0\b",
    r"(?i)Myfaces\d?\b",
    r"(?i)Wicket\d?\b",
    r"(?i)URLDNS\b",
    r"(?i)Clojure\b.*payload",
    r"(?i)readObject\s*\(",
    r"(?i)readResolve\s*\(",
    r"(?i)readExternal\s*\(",
    r"(?i)ObjectInputStream\b",
    r"(?i)ObjectOutputStream\b",
    r"(?i)writeObject\s*\(",
    r"(?i)Externalizable\b",
    r"(?i)Serializable\b.*proxy",
    r"(?i)InvocationHandler\b",
    r"(?i)LazyMap\b",
    r"(?i)TiedMapEntry\b",
    r"(?i)TransformingComparator\b",
    r"(?i)PriorityQueue\b.*Comparator",
    # --- PHP ---
    r"(?i)O:\d+:\s*\"[^\"]+\":\d+:\s*\{",
    r"(?i)a:\d+:\s*\{",
    r"(?i)s:\d+:\s*\"[^\"]+\"",
    r"(?i)i:\d+;",
    r"(?i)b:[01];",
    r"(?i)(?:[aisObCRr]:\d+[;:{].*)?N;(?:.*[aisObCRr]:\d+[;:{])",
    r"(?i)C:\d+:\s*\"[^\"]+\":\d+:\s*\{",
    r"(?i)R:\d+;",
    r"(?i)r:\d+;",
    r"(?i)__(?:wakeup|destruct|toString|sleep|call|callStatic|get|set|isset|unset|invoke|set_state|clone|debugInfo)\s*\(",
    r"(?i)unserialize\s*\(",
    r"(?i)phar://.*\.(?:phar|gif|jpg|png)",
    r"(?i)php://filter/.*convert\.(?:base64|quoted-printable|iconv)",
    r"(?i)Monolog\\Handler",
    r"(?i)Guzzle\\Psr7\b",
    r"(?i)Symfony\\Component\b",
    r"(?i)Illuminate\\(?:Broadcasting|Database|Queue|Support)\b",
    r"(?i)PendingBroadcast\b",
    r"(?i)FnStream\b",
    r"(?i)MockPhpStream\b",
    r"(?i)EvalLoader\b",
    r"(?i)phpggc\b",
    # --- Python ---
    r"(?i)pickle\.(?:loads|load|Unpickler|dumps|dump)\s*\(",
    r"(?i)cPickle\.(?:loads|load|Unpickler)\s*\(",
    r"(?i)yaml\.(?:load|unsafe_load|full_load|safe_load)\s*\(",
    r"(?i)yaml\.(?:UnsafeLoader|FullLoader|Loader)\b",
    r"(?i)marshal\.(?:loads|load)\s*\(",
    r"(?i)shelve\.open\s*\(",
    r"(?i)jsonpickle\.(?:decode|encode)\s*\(",
    r"(?i)dill\.(?:loads|load)\s*\(",
    r"(?i)cloudpickle\.\w+\s*\(",
    r"(?i)__reduce__\b",
    r"(?i)__reduce_ex__\b",
    r"(?i)__setstate__\b",
    r"(?i)__getstate__\b",
    r"(?i)cos\nsystem\n",
    r"(?i)cposix\nsystem\n",
    r"(?i)csubprocess\nPopen\n",
    r"(?i)cbuiltins\neval\n",
    r"(?i)c__builtin__\neval\n",
    r"(?i)cos\npopen\n",
    # --- .NET ---
    r"(?i)BinaryFormatter\b",
    r"(?i)SoapFormatter\b",
    r"(?i)NetDataContractSerializer\b",
    r"(?i)LosFormatter\b",
    r"(?i)ObjectStateFormatter\b",
    r"(?i)XmlSerializer\b.*deserialize",
    r"(?i)DataContractSerializer\b",
    r"(?i)JavaScriptSerializer\b",
    r"(?i)Json\.Net\b.*TypeNameHandling",
    r"(?i)TypeNameHandling\.(?:All|Auto|Objects|Arrays)\b",
    r"(?i)__type\s*['\"]?\s*:\s*['\"]?System\.",
    r"(?i)\$type\s*['\"]?\s*:\s*['\"]?System\.",
    r"(?i)ObjectDataProvider\b",
    r"(?i)WindowsIdentity\b",
    r"(?i)System\.Configuration\.Install\.\w+",
    r"(?i)System\.Activities\.\w+",
    r"(?i)System\.Data\.Services\.\w+",
    r"(?i)System\.Windows\.Data\.\w+",
    r"(?i)System\.Windows\.Markup\.\w+",
    r"(?i)System\.Workflow\.\w+",
    r"(?i)System\.CodeDom\.\w+",
    r"(?i)ActivitySurrogateSelector\b",
    r"(?i)ClaimsPrincipal\b",
    r"(?i)SessionSecurityToken\b",
    r"(?i)TextFormattingRunProperties\b",
    r"(?i)TypeConfuseDelegate\b",
    r"(?i)PSObject\b.*deserialize",
    r"(?i)ysoserial\.net\b",
    # --- Ruby ---
    r"(?i)Marshal\.(?:load|restore)\s*\(",
    r"(?i)YAML\.(?:load|unsafe_load|parse)\s*\(",
    r"(?i)ERB\.new\s*\(",
    r"(?i)Gem::Installer\b",
    r"(?i)Gem::Requirement\b",
    r"(?i)Gem::StubSpecification\b",
    r"(?i)DRb::DRbUnknown\b",
    r"(?i)ActiveRecord::Base\b.*destroy",
    r"(?i)Rack::Utils\b",
    r"(?i)ERB\.new\b.*result",
    # --- Node.js ---
    r"(?i)node-serialize\b",
    r"(?i)funcster\b",
    r"(?i)cryo\b",
    r"(?i)serialize-javascript\b",
    r"(?i)_$$ND_FUNC$$_",
    r"(?i)require\s*\(\s*['\"]child_process['\"]",
    r"(?i)Function\s*\(\s*['\"]return\s+this['\"]",
    r"(?i)global\.process\.mainModule\.require",
]

# ============================================================================
# 9. FILE UPLOAD & WEBSHELL (150 patterns)
# ============================================================================
FILE_UPLOAD_DEEP = [
    # --- Dangerous extensions ---
    r"(?i)\.(?:php[2-8]?|phtml|pht|phps|phar|pgif|shtml|inc)\b",
    r"(?i)\.(?:asp|aspx|asmx|ashx|asa|asax|ascx|axd|cshtml|vbhtml)\b",
    r"(?i)\.(?:jsp|jspx|jsw|jsv|jspf|jtml|do|action)\b",
    r"(?i)\.(?:cfm|cfml|cfc|dbm|cgi|pl|py|rb|lua)\b",
    r"(?i)\.(?:sh|bash|zsh|ksh|csh|bat|cmd|ps1|psm1|psd1)\b",
    r"(?i)\.(?:exe|dll|scr|pif|cpl|msi|msp|mst)\b",
    r"(?i)\.(?:vbs|vbe|wsf|wsc|wsh|hta|sct|inf|reg)\b",
    r"(?i)\.(?:jar|war|ear|class|jnlp)\b",
    r"(?i)\.(?:swf|swc|fla|flv)\b",
    r"(?i)\.(?:svg|xml|xsl|xslt|xsd|dtd|rdf|atom|rss)\b.*(?:script|onload|onerror|eval)",
    r"(?i)\.(?:htaccess|htpasswd|htdigest)\b",
    # --- Double extensions ---
    r"(?i)\.\w+\.(?:php|asp|aspx|jsp|cgi|pl|py|rb|sh|bat|cmd|exe|dll)\b",
    r"(?i)\.(?:jpg|jpeg|gif|png|bmp|ico|webp|tiff?)\.(?:php|asp|jsp|pl|py|cgi)\b",
    r"(?i)\.(?:doc|docx|xls|xlsx|pdf|txt|csv)\.(?:php|asp|jsp|exe)\b",
    r"(?i)\.(?:php|asp|jsp|exe)\s*(?:%00|\\x00|\x00)\.(?:jpg|gif|png|pdf)\b",
    # --- Content-Type manipulation ---
    r"(?i)Content-Type:\s*(?:application/x-httpd-php|application/x-php|text/x-php)",
    r"(?i)Content-Type:\s*(?:application/x-asp|application/x-aspx|application/x-jsp)",
    r"(?i)Content-Type:\s*(?:application/x-sh|application/x-csh|application/x-bash)",
    r"(?i)Content-Type:\s*(?:application/x-msdownload|application/x-executable|application/x-msdos-program)",
    r"(?i)Content-Type:\s*(?:image/(?:gif|jpeg|png|svg\+xml)).*(?:php|script|exec)",
    # --- Magic bytes / signatures ---
    r"(?i)(?:GIF89a|GIF87a).*<\?(?:php|=)",
    r"(?i)%PDF-.*<\?(?:php|=)",
    r"(?i)\x89PNG.*<\?(?:php|=)",
    r"(?i)\xff\xd8\xff.*<\?(?:php|=)",
    # --- PHP webshells ---
    r"(?i)<\?(?:php)?\s*(?:eval|assert|preg_replace|create_function|call_user_func|call_user_func_array)\s*\(",
    r"(?i)<\?(?:php)?\s*(?:system|exec|shell_exec|passthru|popen|proc_open|pcntl_exec)\s*\(",
    r"(?i)<\?(?:php)?\s*(?:base64_decode|gzinflate|gzuncompress|str_rot13|strrev)\s*\(",
    r"(?i)<\?(?:php)?\s*\$\w+\s*\(\s*\$\w+\s*\)",
    r"(?i)<\?(?:php)?\s*\$\w+\s*=\s*(?:str_replace|base64_decode|gzinflate|eval|create_function)\s*\(",
    r"(?i)<\?(?:php)?\s*\$\w+\s*=\s*\$_(?:GET|POST|REQUEST|COOKIE|SERVER|FILES|SESSION|ENV)\s*\[",
    r"(?i)<\?=\s*\$_(?:GET|POST|REQUEST|COOKIE)\s*\[",
    r"(?i)(?:c99|r57|b374k|WSO|FilesMan|Ace|IndoXploit|Alfa|Weevely|PhpSpy|p0wny|mini)\s*(?:shell|webshell)",
    r"(?i)(?:phpinfo|phpversion|php_uname|get_current_user|getmyuid|getmypid|get_cfg_var|ini_get|php_sapi_name)\s*\(\s*\)",
    r"(?i)(?:highlight_file|show_source|readfile|file_get_contents|fgets|fread|fpassthru)\s*\(",
    r"(?i)(?:move_uploaded_file|copy|rename|unlink|rmdir|mkdir|chmod|chown|chgrp)\s*\(",
    r"(?i)(?:file_put_contents|fwrite|fputs)\s*\(\s*['\"].*\.\w+['\"]",
    r"(?i)(?:include|require|include_once|require_once)\s*\(\s*\$_(?:GET|POST|REQUEST|COOKIE|SERVER)",
    r"(?i)\$_FILES\s*\[['\"].*['\"]\]\s*\[['\"](?:tmp_name|name|type|size)['\"]",
    r"(?i)preg_replace\s*\(\s*['\"]/.*/e['\"]",
    r"(?i)assert\s*\(\s*\$_(?:GET|POST|REQUEST|COOKIE)",
    r"(?i)array_map\s*\(\s*['\"](?:system|exec|passthru|shell_exec)['\"]",
    r"(?i)array_filter\s*\(\s*\$\w+\s*,\s*['\"](?:system|exec|shell_exec)['\"]",
    r"(?i)usort\s*\(\s*\$\w+\s*,\s*['\"](?:system|exec|shell_exec|assert)['\"]",
    r"(?i)register_shutdown_function\s*\(\s*['\"](?:system|exec|shell_exec)['\"]",
    # --- JSP webshells ---
    r"(?i)<%\s*(?:Runtime|ProcessBuilder|Thread|Class|ClassLoader|URLClassLoader)\.",
    r"(?i)Runtime\.getRuntime\(\)\.exec\s*\(",
    r"(?i)new\s+ProcessBuilder\s*\(",
    r"(?i)<%\s*(?:out\.print|response\.getWriter|request\.getParameter)\b",
    r"(?i)request\.getParameter\s*\(\s*['\"](?:cmd|command|exec|c|x|shell|run|action|do)['\"]",
    r"(?i)ScriptEngine\w*\s*=\s*new\s+ScriptEngineManager",
    # --- ASP webshells ---
    r"(?i)<%\s*(?:Response\.Write|Server\.Execute|Server\.Transfer|Server\.CreateObject)\b",
    r"(?i)Server\.CreateObject\s*\(\s*['\"](?:WScript\.Shell|Shell\.Application|Scripting\.FileSystemObject)['\"]",
    r"(?i)CreateObject\s*\(\s*['\"](?:ADODB\.Stream|Microsoft\.XMLHTTP|Scripting\.Dictionary)['\"]",
    r"(?i)Set\s+\w+\s*=\s*CreateObject\s*\(\s*['\"]WScript",
    r"(?i)Execute\s*\(\s*Request\s*\(",
    r"(?i)eval\s*\(\s*Request\s*\(",
    # --- Python webshells ---
    r"(?i)os\.(?:system|popen|popen2|popen3|popen4|exec\w*)\s*\(",
    r"(?i)subprocess\.(?:Popen|call|run|check_output|check_call|getstatusoutput)\s*\(",
    r"(?i)commands\.(?:getstatusoutput|getoutput)\s*\(",
    r"(?i)exec\s*\(\s*(?:compile|open|request\.|input\(|raw_input\()\b",
    r"(?i)eval\s*\(\s*(?:compile|request\.\w+|__import__)\b",
    r"(?i)__import__\s*\(\s*['\"](?:os|subprocess|commands|pty|socket|shutil)['\"]",
    r"(?i)importlib\.import_module\s*\(\s*['\"](?:os|subprocess)['\"]",
    # --- General webshell indicators ---
    r"(?i)(?:cmd|command|exec|shell|run|action|do)\s*=\s*(?:id|whoami|cat\s|ls\s|dir\s|pwd|uname|ifconfig|ipconfig)",
    r"(?i)FileBrowser|FileManager|WebConsole|Terminal|ShellCommander|CommandExecutor",
]

# ============================================================================
# 10. CRLF / HTTP SMUGGLING / REQUEST SPLITTING (100 patterns)
# ============================================================================
CRLF_SMUGGLING_DEEP = [
    # --- CRLF injection ---
    r"(?i)%0d%0a(?:Set-Cookie|Location|Content-Type|X-|HTTP/):",
    r"(?i)%0d%0a%0d%0a(?:<|{|\[)",
    r"(?i)%0a(?:Set-Cookie|Location|Content-Type|X-|HTTP/):",
    r"(?i)%0d(?:Set-Cookie|Location|Content-Type|X-|HTTP/):",
    r"(?i)\\r\\n(?:Set-Cookie|Location|Content-Type|HTTP/):",
    r"(?i)\r\n(?:Set-Cookie|Location|Content-Type|HTTP/):",
    r"(?i)%E5%98%8A%E5%98%8D(?:Set-Cookie|Location|HTTP/):",
    r"(?i)%c0%8d%c0%8a(?:Set-Cookie|Location|HTTP/):",
    r"(?i)%u000d%u000a(?:Set-Cookie|Location|HTTP/):",
    r"(?i)%250d%250a(?:Set-Cookie|Location|HTTP/):",
    # --- HTTP request smuggling ---
    r"(?i)Transfer-Encoding\s*:\s*chunked.*Content-Length\s*:",
    r"(?i)Content-Length\s*:\s*\d+.*Transfer-Encoding\s*:\s*chunked",
    r"(?i)Transfer-Encoding\s*:\s*(?:chunked|compress|deflate|gzip|identity)\s*,\s*chunked",
    r"(?i)Transfer-Encoding\s*:\s*xchunked",
    r"(?i)Transfer-Encoding\s*:\s*chunked\s*\r?\n\s*Transfer-Encoding\s*:",
    r"(?i)Transfer[\s-]Encoding\s*:\s*chunked",
    r"(?i)Transfer-Encoding\s*:\s*\x00chunked",
    r"(?i)Transfer-Encoding\s*:\s*[\t ]+chunked",
    r"(?i)Transfer-Encoding:\s*chunked\s*;\s*\w+=",
    r"(?i)Transfer-encoding\s*:\s*cow",
    r"(?i)Transfer-Encoding:\s*chu\r?\ncked",
    r"(?i)Content-Length\s*:\s*\d+\s*\r?\n\s*Content-Length\s*:\s*\d+",
    r"(?i)Content-Length\s*:\s*-\d+",
    r"(?i)Content-Length\s*:\s*0\s*\r?\n\s*\r?\n(?:GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)\s+/",
    r"(?i)0\s*\r?\n\s*\r?\n(?:GET|POST|PUT|DELETE)\s+/",
    # --- HTTP response splitting ---
    r"(?i)HTTP/1\.\d\s+200\s+OK\s*\r?\n",
    r"(?i)HTTP/1\.\d\s+301\s+",
    r"(?i)HTTP/1\.\d\s+302\s+",
    r"(?i)Location:\s*https?://[^\s]+\s*\r?\n",
    # --- HTTP verb tampering ---
    r"(?i)^(?:PROPFIND|PROPPATCH|MKCOL|COPY|MOVE|LOCK|UNLOCK|MKCALENDAR)\s+/",
    r"(?i)^(?:REPORT|SEARCH|CHECKOUT|MKACTIVITY|MERGE|SUBSCRIBE|UNSUBSCRIBE)\s+/",
    r"(?i)^(?:TRACE|TRACK|CONNECT|DEBUG|PURGE|LINK|UNLINK|VIEW)\s+/",
    r"(?i)X-HTTP-Method(?:-Override)?\s*:\s*(?:PUT|DELETE|PATCH|TRACE|CONNECT|OPTIONS|DEBUG)",
    r"(?i)X-Method-Override\s*:\s*(?:PUT|DELETE|PATCH|TRACE)",
    # --- HTTP/2 specific ---
    r"(?i):method\s*:\s*(?:TRACE|TRACK|CONNECT|DEBUG|PURGE)",
    r"(?i):path\s*:\s*[^\s]*(?:%0d|%0a|\r|\n)",
    r"(?i):authority\s*:\s*[^\s]*(?:%0d|%0a|\r|\n)",
    r"(?i):scheme\s*:\s*(?:ftp|file|gopher|dict|ldap)",
    # --- Request smuggling via headers ---
    r"(?i)Forwarded\s*:.*(?:%0d|%0a|\r\n)",
    r"(?i)X-Forwarded-For\s*:.*(?:%0d|%0a|\r\n)",
    r"(?i)Via\s*:.*(?:%0d|%0a|\r\n)",
]

# ============================================================================
# Map all patterns
# ============================================================================
RULES_MEGA_1_MAP = {
    'sqli_mega': SQLI_ADVANCED,
    'xss_mega': XSS_DEEP,
    'cmdi_mega': CMDI_DEEP,
    'path_trav_mega': PATH_TRAVERSAL_DEEP,
    'ssrf_mega': SSRF_DEEP,
    'xxe_xslt_mega': XXE_XSLT_DEEP,
    'ssti_mega': SSTI_DEEP,
    'deser_mega': DESER_DEEP,
    'file_upload_mega': FILE_UPLOAD_DEEP,
    'crlf_smuggle_mega': CRLF_SMUGGLING_DEEP,
}


def get_all_mega1_patterns():
    for category, patterns in RULES_MEGA_1_MAP.items():
        for regex_str in patterns:
            yield (regex_str, category)


def count_mega1_patterns():
    return sum(len(p) for p in RULES_MEGA_1_MAP.values())
