# =============================================================================
# BeeWAF — Kustomization (Géré par ArgoCD)
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ressources core BeeWAF uniquement
resources:
  - secrets.yaml
  - deployment.yaml
  - service.yaml
